// Generated C# sources shipped inside the .unitypackage.
//
// Strategy: the prefab + baked AnimationClip are plain serialized assets, but
// the Unity *Timeline* asset is built in-editor by generated code through the
// official Timeline API (YggSceneTimelineBuilder). Hand-writing .playable
// YAML would hard-code Timeline package script GUIDs and break across
// versions; the builder is version-proof and creates real Spine Timeline
// tracks (spine-timeline extension) when available.
//
// Spine wiring happens automatically: YggSpineAutoWire hooks asset import,
// creates SkeletonGraphic/SkeletonAnimation components on exported spine
// placeholders, assigns the SkeletonDataAssets spine-unity generated, and
// saves the result back into the prefab — no clicks needed.
//
// Script paths/GUIDs are constant across exports, so two exported scenes
// share one copy of the runtime instead of colliding.

export const SCRIPT_PATHS = {
  player: 'Assets/YggSceneStudio/Runtime/YggScenePlayer.cs',
  playerEditor: 'Assets/YggSceneStudio/Editor/YggScenePlayerEditor.cs',
  timelineBuilder: 'Assets/YggSceneStudio/Editor/YggSceneTimelineBuilder.cs',
  packageBootstrap: 'Assets/YggSceneStudio/Editor/YggPackageBootstrap.cs',
  spineAutoWire: 'Assets/YggSceneStudio/Editor/YggSpineAutoWire.cs',
  runtimeAsmdef: 'Assets/YggSceneStudio/Runtime/Ygg.SceneStudio.Runtime.asmdef',
  editorAsmdef: 'Assets/YggSceneStudio/Editor/Ygg.SceneStudio.Editor.asmdef'
};

/**
 * .unitypackage files cannot declare UPM dependencies, so this editor
 * bootstrap detects missing packages after import and offers a one-click
 * install through the Package Manager API: com.unity.timeline, and — when
 * the spine-unity runtime is present — the official spine-timeline
 * extension (https://esotericsoftware.com/spine-unity-timeline).
 */
export function packageBootstrapSource() {
  return `// Auto-generated by YGG Toolkit Scene Studio.
using System;
using System.Collections.Generic;
using UnityEditor;
using UnityEditor.PackageManager;
using UnityEngine;

namespace Ygg.SceneStudio
{
    public static class YggPackageBootstrap
    {
        const string SessionKey = "Ygg.SceneStudio.PackagesPrompted";
        // Keep the branch suffix in sync with the project's spine-unity
        // runtime major.minor (this matches a 4.2 runtime install).
        const string SpineTimelinePackage =
            "https://github.com/EsotericSoftware/spine-runtimes.git?path=spine-unity/Modules/com.esotericsoftware.spine.timeline#4.2";

        [InitializeOnLoadMethod]
        static void EnsurePackages()
        {
            var missing = new List<string>();
            var missingNames = new List<string>();

            if (Type.GetType("UnityEngine.Timeline.TimelineAsset, Unity.Timeline") == null)
            {
                missing.Add("com.unity.timeline");
                missingNames.Add("Unity Timeline (com.unity.timeline)");
            }
            bool spineRuntime = Type.GetType("Spine.Unity.SkeletonGraphic, spine-unity") != null;
            if (spineRuntime && Type.GetType("Spine.Unity.Playables.SpineAnimationStateClip, spine-timeline") == null)
            {
                missing.Add(SpineTimelinePackage);
                missingNames.Add("Spine Timeline extension (com.esotericsoftware.spine.timeline @4.2)");
            }
            if (missing.Count == 0) return;
            if (SessionState.GetBool(SessionKey, false)) return;
            SessionState.SetBool(SessionKey, true);

            EditorApplication.delayCall += () =>
            {
                string list = "  \\u2022 " + string.Join("\\n  \\u2022 ", missingNames);
                bool install = EditorUtility.DisplayDialog(
                    "YGG Scene Studio",
                    "The exported scene uses Unity Timeline with Spine tracks. Missing packages:\\n\\n" + list + "\\n\\nInstall now via the Package Manager?",
                    "Install", "Not now");
                if (!install)
                {
                    Debug.Log("[Ygg] Skipped package install - \\u25B6 Play still works via clip sampling + runtime spine cues.");
                    return;
                }
#if UNITY_2021_2_OR_NEWER
                Client.AddAndRemove(missing.ToArray());
#else
                Client.Add(missing[0]);
                if (missing.Count > 1) Debug.LogWarning("[Ygg] Install the remaining package manually: " + missing[1]);
#endif
                Debug.Log("[Ygg] Installing packages via Package Manager: " + string.Join(", ", missingNames));
            };
        }
    }
}
`;
}

// Assembly definitions isolate the generated scripts from Assembly-CSharp
// (a compile error in either side can't break the other) and provide the
// YGG_HAS_TIMELINE define only when com.unity.timeline is installed —
// without it the Timeline builder compiles to a stub and ▶ Play falls back
// to direct clip sampling.
export function runtimeAsmdefSource() {
  return JSON.stringify({
    name: 'Ygg.SceneStudio.Runtime',
    rootNamespace: 'Ygg.SceneStudio',
    references: [],
    includePlatforms: [],
    excludePlatforms: [],
    allowUnsafeCode: false,
    overrideReferences: false,
    precompiledReferences: [],
    autoReferenced: true,
    defineConstraints: [],
    versionDefines: [],
    noEngineReferences: false
  }, null, 2);
}

export function editorAsmdefSource() {
  return JSON.stringify({
    name: 'Ygg.SceneStudio.Editor',
    rootNamespace: 'Ygg.SceneStudio',
    references: ['Ygg.SceneStudio.Runtime', 'Unity.Timeline'],
    includePlatforms: ['Editor'],
    excludePlatforms: [],
    allowUnsafeCode: false,
    overrideReferences: false,
    precompiledReferences: [],
    autoReferenced: true,
    defineConstraints: [],
    versionDefines: [
      { name: 'com.unity.timeline', expression: '', define: 'YGG_HAS_TIMELINE' }
    ],
    noEngineReferences: false
  }, null, 2);
}

export function scenePlayerSource() {
  return `// Auto-generated by YGG Toolkit Scene Studio. Safe to re-import; shared
// across exported scene packages.
using System;
using System.Collections.Generic;
using System.Reflection;
using UnityEngine;
using UnityEngine.Playables;

namespace Ygg.SceneStudio
{
    [Serializable]
    public class SpineCue
    {
        public string target;
        public string animationName;
        public float start;
        public float duration;
        public float speed = 1f;
        public bool loop = true;
        public float mixDuration = -1f;
        public int trackIndex;
    }

    /// <summary>
    /// Plays the exported scene: drives the PlayableDirector (when a Timeline
    /// was built via Ygg > Build Timeline) or samples the baked
    /// AnimationClip directly, and fires Spine AnimationState cues by
    /// reflection so the script compiles without spine-unity installed.
    /// </summary>
    public class YggScenePlayer : MonoBehaviour
    {
        public PlayableDirector director;
        public AnimationClip transformClip;
        public TextAsset descriptor;
        public float durationSeconds = 5f;
        public List<SpineCue> spineCues = new List<SpineCue>();
        /// Set by the Timeline builder once Spine Timeline tracks exist —
        /// the runtime cue fallback then steps aside to avoid double-firing.
        public bool spineCuesHandledByTimeline;

        bool playing;
        float elapsed;
        readonly HashSet<int> fired = new HashSet<int>();

        public bool IsPlaying => playing || (director != null && director.playableAsset != null && director.state == PlayState.Playing);

        public void Play()
        {
            StopInternal();
            fired.Clear();
            elapsed = 0f;
            if (director != null && director.playableAsset != null)
            {
                director.time = 0;
                director.Play();
            }
            playing = true;
        }

        public void Stop()
        {
            StopInternal();
            if (transformClip != null) transformClip.SampleAnimation(gameObject, 0f);
        }

        void StopInternal()
        {
            playing = false;
            if (director != null && director.playableAsset != null) director.Stop();
        }

        void Update()
        {
            if (!playing) return;
            bool directorDriven = director != null && director.playableAsset != null;
            float t = directorDriven ? (float)director.time : elapsed;

            if (!directorDriven)
            {
                elapsed += Time.deltaTime;
                if (transformClip != null) transformClip.SampleAnimation(gameObject, Mathf.Min(t, transformClip.length));
            }

            if (!(directorDriven && spineCuesHandledByTimeline))
            {
                for (int i = 0; i < spineCues.Count; i++)
                {
                    if (fired.Contains(i)) continue;
                    var cue = spineCues[i];
                    if (t + 1e-4f < cue.start) continue;
                    fired.Add(i);
                    FireSpineCue(cue);
                }
            }

            if (t >= durationSeconds && !directorDriven) playing = false;
            if (directorDriven && director.state != PlayState.Playing && t > 0) playing = false;
        }

        void FireSpineCue(SpineCue cue)
        {
            var child = string.IsNullOrEmpty(cue.target) ? transform : transform.Find(cue.target);
            if (child == null) { Debug.LogWarning($"[YggScenePlayer] spine cue target not found: {cue.target}"); return; }
            foreach (var comp in child.GetComponents<MonoBehaviour>())
            {
                if (comp == null) continue;
                var type = comp.GetType();
                if (type.FullName != "Spine.Unity.SkeletonGraphic" && type.FullName != "Spine.Unity.SkeletonAnimation") continue;
                var stateProp = type.GetProperty("AnimationState", BindingFlags.Public | BindingFlags.Instance);
                var state = stateProp != null ? stateProp.GetValue(comp) : null;
                if (state == null) { Debug.LogWarning($"[YggScenePlayer] {type.Name} on {child.name} has no AnimationState (SkeletonDataAsset assigned?)"); return; }
                var setAnim = state.GetType().GetMethod("SetAnimation", new[] { typeof(int), typeof(string), typeof(bool) });
                if (setAnim == null) return;
                var entry = setAnim.Invoke(state, new object[] { cue.trackIndex, cue.animationName, cue.loop });
                if (entry != null)
                {
                    var entryType = entry.GetType();
                    if (cue.mixDuration >= 0f)
                        entryType.GetProperty("MixDuration")?.SetValue(entry, cue.mixDuration);
                    if (Math.Abs(cue.speed - 1f) > 1e-4f)
                        entryType.GetProperty("TimeScale")?.SetValue(entry, cue.speed);
                }
                return;
            }
            Debug.LogWarning($"[YggScenePlayer] no Spine component on {child.name} — attach SkeletonGraphic/SkeletonAnimation and assign its SkeletonDataAsset.");
        }
    }
}
`;
}

/**
 * Auto-wiring of exported spine placeholders. Runs on package import (and
 * once per editor session, covering the very first import while these
 * scripts were still compiling), creating the spine components and saving
 * the SkeletonDataAsset references back into the prefab asset.
 */
export function spineAutoWireSource() {
  return `// Auto-generated by YGG Toolkit Scene Studio.
using System;
using System.Collections.Generic;
using System.IO;
using UnityEditor;
using UnityEngine;

namespace Ygg.SceneStudio
{
    public static class YggSpineAutoWire
    {
        [Serializable] public class DescriptorNode
        {
            public string path;
            public string kind;
            public string spineData;
            public string spineSkin;
            public string spineAnim;
            public bool spineLoop = true;
        }
        [Serializable] public class Descriptor { public string variant; public List<DescriptorNode> nodes; }

        /// <summary>
        /// Create-or-find the spine component on every exported spine node and
        /// assign SkeletonDataAsset/skin/animation from the descriptor.
        /// Returns the number of CHANGES applied (0 = already fully wired);
        /// unresolved counts nodes that could not be wired yet.
        /// </summary>
        public static int Wire(YggScenePlayer player, out int unresolved, bool interactive = true)
        {
            unresolved = 0;
            if (player == null || player.descriptor == null)
            {
                if (interactive) Debug.LogWarning("[Ygg] No descriptor TextAsset on the player — cannot auto-wire spine.");
                return 0;
            }
            Descriptor desc;
            try { desc = JsonUtility.FromJson<Descriptor>(player.descriptor.text); }
            catch (Exception e) { Debug.LogError("[Ygg] Failed to parse descriptor: " + e.Message); return 0; }
            if (desc?.nodes == null) return 0;

            var dataAssets = new List<(string name, string path)>();
            foreach (var guid in AssetDatabase.FindAssets("t:SkeletonDataAsset"))
            {
                var p = AssetDatabase.GUIDToAssetPath(guid);
                dataAssets.Add((Path.GetFileNameWithoutExtension(p), p));
            }

            int changes = 0;
            foreach (var node in desc.nodes)
            {
                if (string.IsNullOrEmpty(node.spineData)) continue;
                var child = string.IsNullOrEmpty(node.path) ? player.transform : player.transform.Find(node.path);
                if (child == null) { Debug.LogWarning($"[Ygg] spine node not found: {node.path}"); unresolved++; continue; }

                MonoBehaviour spineComp = null;
                foreach (var comp in child.GetComponents<MonoBehaviour>())
                {
                    if (comp == null) continue;
                    var fn = comp.GetType().FullName;
                    if (fn == "Spine.Unity.SkeletonGraphic" || fn == "Spine.Unity.SkeletonAnimation") { spineComp = comp; break; }
                }
                if (spineComp == null)
                {
                    string wantedType = desc.variant == "world"
                        ? "Spine.Unity.SkeletonAnimation, spine-unity"
                        : "Spine.Unity.SkeletonGraphic, spine-unity";
                    var t = Type.GetType(wantedType);
                    if (t == null)
                    {
                        if (interactive) Debug.LogWarning($"[Ygg] spine-unity runtime not found ({wantedType}) — cannot create component for {node.path}.");
                        unresolved++;
                        continue;
                    }
                    // AddComponent runs spine-unity's own editor defaults —
                    // materials auto-detected exactly like adding it by hand.
                    spineComp = interactive
                        ? (MonoBehaviour)Undo.AddComponent(child.gameObject, t)
                        : (MonoBehaviour)child.gameObject.AddComponent(t);
                    Debug.Log($"[Ygg] {node.path}: added {t.Name}", spineComp);
                    changes++;
                }

                var so = new SerializedObject(spineComp);
                var dataProp = so.FindProperty("skeletonDataAsset");
                if (dataProp == null) { unresolved++; continue; }

                if (dataProp.objectReferenceValue == null)
                {
                    string want = node.spineData + "_SkeletonData";
                    string found = null;
                    foreach (var (name, p) in dataAssets)
                    {
                        if (string.Equals(name, want, StringComparison.OrdinalIgnoreCase)) { found = p; break; }
                        if (found == null && name.StartsWith(node.spineData, StringComparison.OrdinalIgnoreCase)) found = p;
                    }
                    if (found == null)
                    {
                        if (interactive) Debug.LogWarning($"[Ygg] No SkeletonDataAsset found for '{node.spineData}' — has spine-unity imported the skeleton yet?");
                        unresolved++;
                        continue;
                    }
                    dataProp.objectReferenceValue = AssetDatabase.LoadAssetAtPath<UnityEngine.Object>(found);
                    Debug.Log($"[Ygg] {node.path} \\u2190 {found}", spineComp);
                }

                SetString(so, "initialSkinName", string.IsNullOrEmpty(node.spineSkin) ? "default" : node.spineSkin);
                SetString(so, "startingAnimation", node.spineAnim);   // SkeletonGraphic
                SetString(so, "_animationName", node.spineAnim);      // SkeletonAnimation
                SetBool(so, "startingLoop", node.spineLoop);
                SetBool(so, "loop", node.spineLoop);
                if (so.ApplyModifiedProperties()) changes++;
                EditorUtility.SetDirty(spineComp);
            }
            if (interactive) Debug.Log($"[Ygg] Spine auto-wire done: {changes} change(s), {unresolved} unresolved.");
            return changes;
        }

        /// <summary>
        /// Open a prefab asset, wire it, and save it back when changed.
        /// Returns true when fully resolved (no retry needed).
        /// </summary>
        public static bool WirePrefabAtPath(string prefabPath)
        {
            var root = PrefabUtility.LoadPrefabContents(prefabPath);
            try
            {
                var player = root.GetComponentInChildren<YggScenePlayer>();
                if (player == null) return true;
                int changes = Wire(player, out int unresolved, interactive: false);
                if (changes > 0)
                {
                    PrefabUtility.SaveAsPrefabAsset(root, prefabPath);
                    Debug.Log($"[Ygg] Auto-wired spine in {prefabPath} ({changes} change(s)).");
                }
                return unresolved == 0;
            }
            finally
            {
                PrefabUtility.UnloadPrefabContents(root);
            }
        }

        // ── automatic wiring on package import ────────────────────────────
        class ImportHook : AssetPostprocessor
        {
            static void OnPostprocessAllAssets(string[] imported, string[] deleted, string[] moved, string[] movedFrom)
            {
                var prefabs = new List<string>();
                foreach (var p in imported)
                    if (p.EndsWith(".prefab", StringComparison.OrdinalIgnoreCase)) prefabs.Add(p);
                if (prefabs.Count > 0) SchedulePrefabWiring(prefabs, 8);
            }
        }

        static void SchedulePrefabWiring(List<string> prefabPaths, int retries)
        {
            EditorApplication.delayCall += () =>
            {
                if (EditorApplication.isCompiling || EditorApplication.isUpdating)
                {
                    if (retries > 0) SchedulePrefabWiring(prefabPaths, retries - 1);
                    return;
                }
                var remaining = new List<string>();
                foreach (var path in prefabPaths)
                {
                    var go = AssetDatabase.LoadAssetAtPath<GameObject>(path);
                    if (go == null || go.GetComponentInChildren<YggScenePlayer>() == null) continue;
                    bool complete;
                    try { complete = WirePrefabAtPath(path); }
                    catch (Exception e) { Debug.LogWarning($"[Ygg] auto-wire failed for {path}: {e.Message}"); continue; }
                    // SkeletonDataAssets may not be generated yet on the first
                    // pass — retry on later editor ticks.
                    if (!complete) remaining.Add(path);
                }
                if (remaining.Count > 0 && retries > 0) SchedulePrefabWiring(remaining, retries - 1);
            };
        }

        // Once per session: covers the very first package import, when these
        // scripts were still compiling while the prefab was imported.
        [InitializeOnLoadMethod]
        static void SessionSweep()
        {
            if (SessionState.GetBool("Ygg.AutoWire.Swept", false)) return;
            SessionState.SetBool("Ygg.AutoWire.Swept", true);
            EditorApplication.delayCall += () =>
            {
                var prefabs = new List<string>();
                foreach (var guid in AssetDatabase.FindAssets("_timeline t:TextAsset"))
                {
                    var descPath = AssetDatabase.GUIDToAssetPath(guid);
                    var dir = Path.GetDirectoryName(descPath);
                    if (string.IsNullOrEmpty(dir)) continue;
                    foreach (var pguid in AssetDatabase.FindAssets("t:Prefab", new[] { dir.Replace('\\\\', '/') }))
                    {
                        var p = AssetDatabase.GUIDToAssetPath(pguid);
                        if (!prefabs.Contains(p)) prefabs.Add(p);
                    }
                }
                if (prefabs.Count > 0) SchedulePrefabWiring(prefabs, 2);
            };
        }

        static void SetString(SerializedObject so, string prop, string value)
        {
            var p = so.FindProperty(prop);
            if (p != null && value != null && p.stringValue != value) p.stringValue = value;
        }

        static void SetBool(SerializedObject so, string prop, bool value)
        {
            var p = so.FindProperty(prop);
            if (p != null && p.boolValue != value) p.boolValue = value;
        }
    }
}
`;
}

export function scenePlayerEditorSource() {
  return `// Auto-generated by YGG Toolkit Scene Studio.
using UnityEditor;
using UnityEngine;

namespace Ygg.SceneStudio
{
    [CustomEditor(typeof(YggScenePlayer))]
    // Fully qualified base class: projects with a DLL exposing a root-level
    // "Editor" namespace would otherwise shadow UnityEditor.Editor (CS0118).
    public class YggScenePlayerEditor : UnityEditor.Editor
    {
        public override void OnInspectorGUI()
        {
            DrawDefaultInspector();
            var player = (YggScenePlayer)target;

            EditorGUILayout.Space();
            if (GUILayout.Button("Auto-assign Spine Data"))
            {
                YggSpineAutoWire.Wire(player, out _);
            }
            if (GUILayout.Button("Build Unity Timeline from baked clip"))
            {
                YggSceneTimelineBuilder.Build(player);
            }

            using (new EditorGUI.DisabledScope(!Application.isPlaying))
            {
                EditorGUILayout.BeginHorizontal();
                if (GUILayout.Button("▶ Play")) player.Play();
                if (GUILayout.Button("■ Stop")) player.Stop();
                EditorGUILayout.EndHorizontal();
            }
            if (!Application.isPlaying)
                EditorGUILayout.HelpBox("Spine components are wired automatically on import; the buttons re-run wiring and (re)build the Timeline. Enter Play Mode to use Play/Stop.", MessageType.Info);
        }
    }
}
`;
}

export function timelineBuilderSource() {
  return `// Auto-generated by YGG Toolkit Scene Studio.
//
// Builds a Unity TimelineAsset from the baked AnimationClip + spine cues
// using the official Timeline API — no fragile serialized Timeline YAML.
// With the spine-timeline extension installed, spine cues become REAL
// Spine Animation State tracks/clips (AnimationReferenceAssets are created
// as needed); otherwise the cues stay on YggScenePlayer as a runtime
// fallback.
//
// Compiles to a stub when the com.unity.timeline package is missing
// (YGG_HAS_TIMELINE comes from the asmdef versionDefines) so importing the
// package never breaks the project — ▶ Play then samples the baked clip
// directly instead of driving a PlayableDirector.
#if !YGG_HAS_TIMELINE
using UnityEngine;

namespace Ygg.SceneStudio
{
    public static class YggSceneTimelineBuilder
    {
        public static void Build(YggScenePlayer player)
        {
            Debug.LogWarning("[Ygg] The com.unity.timeline package is not installed — add it via Package Manager to build a Timeline. ▶ Play works without it (direct clip sampling).");
        }
    }
}
#else
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using UnityEditor;
using UnityEngine;
using UnityEngine.Playables;
using UnityEngine.Timeline;

namespace Ygg.SceneStudio
{
    public static class YggSceneTimelineBuilder
    {
        public static void Build(YggScenePlayer player)
        {
            if (player == null) return;
            var director = player.director != null ? player.director : player.GetComponent<PlayableDirector>();
            if (director == null) { Debug.LogError("[Ygg] No PlayableDirector on the scene player."); return; }

            string basePath = GetAssetFolder(player);
            string assetPath = Path.Combine(basePath, player.gameObject.name + "_Timeline.playable").Replace('\\\\', '/');

            var timeline = AssetDatabase.LoadAssetAtPath<TimelineAsset>(assetPath);
            if (timeline == null)
            {
                timeline = ScriptableObject.CreateInstance<TimelineAsset>();
                AssetDatabase.CreateAsset(timeline, assetPath);
            }
            else
            {
                foreach (var t in timeline.GetRootTracks().ToList())
                    timeline.DeleteTrack(t);
            }

            timeline.fixedDuration = player.durationSeconds;
            timeline.durationMode = TimelineAsset.DurationMode.FixedLength;

            if (player.transformClip != null)
            {
                var track = timeline.CreateTrack<AnimationTrack>(null, "Baked transforms");
                var clip = track.CreateClip(player.transformClip);
                clip.start = 0;
                clip.duration = Math.Max(0.05f, player.transformClip.length);
                var animator = player.GetComponent<Animator>();
                if (animator != null) director.SetGenericBinding(track, animator);
            }

            TryBuildSpineTracks(player, timeline, director, basePath.Replace('\\\\', '/'));

            director.playableAsset = timeline;
            EditorUtility.SetDirty(timeline);
            EditorUtility.SetDirty(director);
            EditorUtility.SetDirty(player);
            AssetDatabase.SaveAssets();
            Debug.Log($"[Ygg] Timeline built at {assetPath}", timeline);
        }

        static string GetAssetFolder(YggScenePlayer player)
        {
            // Next to the prefab when the player comes from one, else the clip's folder.
            string src = null;
            var prefab = PrefabUtility.GetCorrespondingObjectFromSource(player.gameObject);
            if (prefab != null) src = AssetDatabase.GetAssetPath(prefab);
            if (string.IsNullOrEmpty(src) && player.transformClip != null) src = AssetDatabase.GetAssetPath(player.transformClip);
            if (string.IsNullOrEmpty(src)) src = "Assets";
            return Path.GetDirectoryName(src);
        }

        static void TryBuildSpineTracks(YggScenePlayer player, TimelineAsset timeline, PlayableDirector director, string assetFolder)
        {
            if (player.spineCues == null || player.spineCues.Count == 0) return;

            var graphicTrackType = Type.GetType("Spine.Unity.Playables.SpineAnimationStateGraphicTrack, spine-timeline");
            var animTrackType = Type.GetType("Spine.Unity.Playables.SpineAnimationStateTrack, spine-timeline");
            var clipType = Type.GetType("Spine.Unity.Playables.SpineAnimationStateClip, spine-timeline");
            var refAssetType = Type.GetType("Spine.Unity.AnimationReferenceAsset, spine-unity");
            if (clipType == null || refAssetType == null || (graphicTrackType == null && animTrackType == null))
            {
                Debug.Log("[Ygg] spine-timeline extension not found — spine cues stay on YggScenePlayer (runtime fallback). Install it via the Ygg bootstrap dialog or Package Manager.");
                player.spineCuesHandledByTimeline = false;
                return;
            }

            var createClip = typeof(TrackAsset).GetMethods(BindingFlags.Public | BindingFlags.Instance)
                .First(m => m.Name == "CreateClip" && m.IsGenericMethod && m.GetParameters().Length == 0)
                .MakeGenericMethod(clipType);

            string refFolder = assetFolder + "/SpineRefs";
            if (!AssetDatabase.IsValidFolder(refFolder))
                AssetDatabase.CreateFolder(assetFolder, "SpineRefs");

            // One track per (target, spine track index), clips in cue order.
            var groups = new Dictionary<string, List<SpineCue>>();
            foreach (var cue in player.spineCues)
            {
                string key = cue.target + "\\u0001" + cue.trackIndex;
                if (!groups.TryGetValue(key, out var list)) groups[key] = list = new List<SpineCue>();
                list.Add(cue);
            }

            int built = 0;
            foreach (var group in groups.Values)
            {
                var first = group[0];
                var child = string.IsNullOrEmpty(first.target) ? player.transform : player.transform.Find(first.target);
                if (child == null) { Debug.LogWarning($"[Ygg] spine cue target not found: {first.target}"); continue; }

                MonoBehaviour spineComp = null;
                bool isGraphic = false;
                foreach (var comp in child.GetComponents<MonoBehaviour>())
                {
                    if (comp == null) continue;
                    var fn = comp.GetType().FullName;
                    if (fn == "Spine.Unity.SkeletonGraphic") { spineComp = comp; isGraphic = true; break; }
                    if (fn == "Spine.Unity.SkeletonAnimation") { spineComp = comp; break; }
                }
                if (spineComp == null) { Debug.LogWarning($"[Ygg] no spine component on {first.target} — run Auto-assign Spine Data first."); continue; }

                var dataAsset = new SerializedObject(spineComp).FindProperty("skeletonDataAsset")?.objectReferenceValue;
                if (dataAsset == null) { Debug.LogWarning($"[Ygg] {first.target}: SkeletonDataAsset not assigned — run Auto-assign Spine Data first."); continue; }

                var trackType = isGraphic ? (graphicTrackType ?? animTrackType) : (animTrackType ?? graphicTrackType);
                var track = timeline.CreateTrack(trackType, null, "Spine: " + first.target);
                var soTrack = new SerializedObject(track);
                var tiProp = soTrack.FindProperty("trackIndex");
                if (tiProp != null) { tiProp.intValue = first.trackIndex; soTrack.ApplyModifiedProperties(); }
                director.SetGenericBinding(track, spineComp);

                foreach (var cue in group.OrderBy(c => c.start))
                {
                    var refAsset = EnsureReferenceAsset(refFolder, dataAsset, cue.animationName, refAssetType);
                    var clip = (TimelineClip)createClip.Invoke(track, null);
                    clip.start = cue.start;
                    clip.duration = Math.Max(0.05, cue.duration);
                    clip.displayName = cue.animationName;
                    if (Math.Abs(cue.speed - 1f) > 1e-4f) clip.timeScale = cue.speed;

                    var soClip = new SerializedObject(clip.asset);
                    SetRef(soClip, "template.animationReference", refAsset);
                    SetBool(soClip, "template.loop", cue.loop);
                    if (cue.mixDuration >= 0f)
                    {
                        SetFloat(soClip, "template.mixDuration", cue.mixDuration);
                        SetBool(soClip, "template.useBlendDuration", false);
                    }
                    soClip.ApplyModifiedProperties();
                }
                built++;
            }

            player.spineCuesHandledByTimeline = built > 0;
            if (built > 0) Debug.Log($"[Ygg] Built {built} Spine Timeline track(s); runtime cues disabled while the director drives playback.");
        }

        /// AnimationReferenceAssets are how Spine Timeline clips reference an
        /// animation — created on demand next to the timeline, reused after.
        static UnityEngine.Object EnsureReferenceAsset(string folder, UnityEngine.Object dataAsset, string animationName, Type refAssetType)
        {
            string safe = string.Concat(animationName.Select(ch => char.IsLetterOrDigit(ch) || ch == '_' || ch == '-' ? ch : '_'));
            string path = folder + "/" + dataAsset.name.Replace("_SkeletonData", "") + "_" + safe + ".asset";
            var existing = AssetDatabase.LoadAssetAtPath<UnityEngine.Object>(path);
            if (existing != null) return existing;

            var asset = ScriptableObject.CreateInstance(refAssetType);
            var so = new SerializedObject(asset);
            var animProp = so.FindProperty("animationName");
            if (animProp != null) animProp.stringValue = animationName;
            SetRef(so, "skeletonDataAsset", dataAsset);
            so.ApplyModifiedProperties();
            AssetDatabase.CreateAsset(asset, path);
            return asset;
        }

        static void SetRef(SerializedObject so, string prop, UnityEngine.Object value)
        {
            var p = so.FindProperty(prop);
            if (p != null) p.objectReferenceValue = value;
        }

        static void SetBool(SerializedObject so, string prop, bool value)
        {
            var p = so.FindProperty(prop);
            if (p != null) p.boolValue = value;
        }

        static void SetFloat(SerializedObject so, string prop, float value)
        {
            var p = so.FindProperty(prop);
            if (p != null) p.floatValue = value;
        }
    }
}
#endif
`;
}
