// Generated C# sources shipped inside the .unitypackage.
//
// Strategy: the prefab + baked AnimationClip are plain serialized assets, but
// the Unity *Timeline* asset is built in-editor by generated code through the
// official Timeline API (YggSceneTimelineBuilder). Hand-writing .playable
// YAML would hard-code Timeline package script GUIDs and break across
// versions; the builder is version-proof and creates real Spine Timeline
// tracks (spine-timeline extension) when available.
//
// Spine wiring happens automatically: YggSpineAutoWire hooks asset import,
// creates SkeletonGraphic/SkeletonAnimation components on exported spine
// placeholders, assigns the SkeletonDataAssets spine-unity generated, and
// saves the result back into the prefab — no clicks needed.
//
// Script paths/GUIDs are constant across exports, so two exported scenes
// share one copy of the runtime instead of colliding.

export const SCRIPT_PATHS = {
  player: 'Assets/YggSceneStudio/Runtime/YggScenePlayer.cs',
  spinner: 'Assets/YggSceneStudio/Runtime/YggSpinner.cs',
  playerEditor: 'Assets/YggSceneStudio/Editor/YggScenePlayerEditor.cs',
  // Timeline-dependent code lives in its OWN assembly, gated by a
  // defineConstraint, so the rest of the editor tooling (package bootstrap,
  // spine auto-wire, inspector) compiles even when com.unity.timeline is
  // absent. A missing by-name asmdef reference is a hard compile error —
  // referencing Unity.Timeline from the main editor asmdef used to kill the
  // whole assembly (and the install dialog with it) on projects without
  // the package.
  timelineBuilder: 'Assets/YggSceneStudio/Editor/Timeline/YggSceneTimelineBuilder.cs',
  packageBootstrap: 'Assets/YggSceneStudio/Editor/YggPackageBootstrap.cs',
  spineAutoWire: 'Assets/YggSceneStudio/Editor/YggSpineAutoWire.cs',
  runtimeAsmdef: 'Assets/YggSceneStudio/Runtime/Ygg.SceneStudio.Runtime.asmdef',
  editorAsmdef: 'Assets/YggSceneStudio/Editor/Ygg.SceneStudio.Editor.asmdef',
  timelineAsmdef: 'Assets/YggSceneStudio/Editor/Timeline/Ygg.SceneStudio.Editor.Timeline.asmdef'
};

/**
 * .unitypackage files cannot declare UPM dependencies, so this editor
 * bootstrap detects missing packages after import and offers a one-click
 * install through the Package Manager API: com.unity.timeline, and — when
 * the spine-unity runtime is present — the official spine-timeline
 * extension (https://esotericsoftware.com/spine-unity-timeline).
 */
export function packageBootstrapSource() {
  return `// Auto-generated by YGG Toolkit Scene Studio.
using System;
using System.Collections.Generic;
using UnityEditor;
using UnityEditor.PackageManager;
using UnityEngine;

namespace Ygg.SceneStudio
{
    public static class YggPackageBootstrap
    {
        const string SessionKey = "Ygg.SceneStudio.PackagesPrompted";
        // Keep the branch suffix in sync with the project's spine-unity
        // runtime major.minor (this matches a 4.2 runtime install).
        const string SpineTimelinePackage =
            "https://github.com/EsotericSoftware/spine-runtimes.git?path=spine-unity/Modules/com.esotericsoftware.spine.timeline#4.2";

        [InitializeOnLoadMethod]
        static void EnsurePackages() { Prompt(false); }

        [MenuItem("Ygg/Scene Studio/Install Required Packages\\u2026")]
        static void InstallMenu() { Prompt(true); }

        static void Prompt(bool manual)
        {
            var missing = new List<string>();
            var missingNames = new List<string>();

            if (Type.GetType("UnityEngine.Timeline.TimelineAsset, Unity.Timeline") == null)
            {
                missing.Add("com.unity.timeline");
                missingNames.Add("Unity Timeline (com.unity.timeline)");
            }
            bool spineRuntime = Type.GetType("Spine.Unity.SkeletonGraphic, spine-unity") != null;
            if (spineRuntime && Type.GetType("Spine.Unity.Playables.SpineAnimationStateClip, spine-timeline") == null)
            {
                missing.Add(SpineTimelinePackage);
                missingNames.Add("Spine Timeline extension (com.esotericsoftware.spine.timeline @4.2)");
            }
            if (missing.Count == 0)
            {
                if (manual) EditorUtility.DisplayDialog("YGG Scene Studio", "All required packages are installed.", "OK");
                return;
            }
            if (!manual)
            {
                // Auto-prompt once per editor session; always re-runnable from
                // Ygg > Scene Studio > Install Required Packages.
                if (SessionState.GetBool(SessionKey, false))
                {
                    Debug.Log("[Ygg] Packages still missing (" + string.Join(", ", missingNames) + ") - use Ygg > Scene Studio > Install Required Packages\\u2026");
                    return;
                }
                SessionState.SetBool(SessionKey, true);
            }

            EditorApplication.delayCall += () =>
            {
                string list = "  \\u2022 " + string.Join("\\n  \\u2022 ", missingNames);
                bool install = EditorUtility.DisplayDialog(
                    "YGG Scene Studio",
                    "The exported scene uses Unity Timeline with Spine tracks. Missing packages:\\n\\n" + list + "\\n\\nInstall now via the Package Manager?",
                    "Install", "Not now");
                if (!install)
                {
                    Debug.Log("[Ygg] Skipped package install - \\u25B6 Play still works via clip sampling + runtime spine cues.");
                    return;
                }
#if UNITY_2021_2_OR_NEWER
                Client.AddAndRemove(missing.ToArray());
#else
                Client.Add(missing[0]);
                if (missing.Count > 1) Debug.LogWarning("[Ygg] Install the remaining package manually: " + missing[1]);
#endif
                Debug.Log("[Ygg] Installing packages via Package Manager: " + string.Join(", ", missingNames));
            };
        }
    }
}
`;
}

// Assembly definitions isolate the generated scripts from Assembly-CSharp
// (a compile error in either side can't break the other) and provide the
// YGG_HAS_TIMELINE define only when com.unity.timeline is installed —
// without it the Timeline builder compiles to a stub and ▶ Play falls back
// to direct clip sampling.
export function runtimeAsmdefSource() {
  return JSON.stringify({
    name: 'Ygg.SceneStudio.Runtime',
    rootNamespace: 'Ygg.SceneStudio',
    references: [],
    includePlatforms: [],
    excludePlatforms: [],
    allowUnsafeCode: false,
    overrideReferences: false,
    precompiledReferences: [],
    autoReferenced: true,
    defineConstraints: [],
    versionDefines: [],
    noEngineReferences: false
  }, null, 2);
}

export function editorAsmdefSource() {
  // No Unity.Timeline reference and no versionDefines here: this assembly
  // must ALWAYS compile (it hosts the package-install bootstrap). Dropping
  // the versionDefine also keeps a stale pre-split YggSceneTimelineBuilder.cs
  // (old package versions placed it in this folder) compiling as its
  // !YGG_HAS_TIMELINE stub instead of erroring.
  return JSON.stringify({
    name: 'Ygg.SceneStudio.Editor',
    rootNamespace: 'Ygg.SceneStudio',
    references: ['Ygg.SceneStudio.Runtime'],
    includePlatforms: ['Editor'],
    excludePlatforms: [],
    allowUnsafeCode: false,
    overrideReferences: false,
    precompiledReferences: [],
    autoReferenced: true,
    defineConstraints: [],
    versionDefines: [],
    noEngineReferences: false
  }, null, 2);
}

export function timelineAsmdefSource() {
  // Compiled ONLY when com.unity.timeline is installed: the versionDefine
  // provides YGG_HAS_TIMELINE and the defineConstraint excludes the whole
  // assembly (reference checks included) when it is missing.
  return JSON.stringify({
    name: 'Ygg.SceneStudio.Editor.Timeline',
    rootNamespace: 'Ygg.SceneStudio',
    references: ['Ygg.SceneStudio.Runtime', 'Unity.Timeline'],
    includePlatforms: ['Editor'],
    excludePlatforms: [],
    allowUnsafeCode: false,
    overrideReferences: false,
    precompiledReferences: [],
    autoReferenced: true,
    defineConstraints: ['YGG_HAS_TIMELINE'],
    versionDefines: [
      { name: 'com.unity.timeline', expression: '', define: 'YGG_HAS_TIMELINE' }
    ],
    noEngineReferences: false
  }, null, 2);
}

export function scenePlayerSource() {
  return `// Auto-generated by YGG Toolkit Scene Studio. Safe to re-import; shared
// across exported scene packages.
using System;
using System.Collections.Generic;
using System.Reflection;
using UnityEngine;
using UnityEngine.Playables;

namespace Ygg.SceneStudio
{
    [Serializable]
    public class SpineCue
    {
        public string target;
        public string animationName;
        public float start;
        public float duration;
        public float speed = 1f;
        public bool loop = true;
        public float mixDuration = -1f;
        public int trackIndex;
    }

    /// <summary>
    /// Plays the exported scene: drives the PlayableDirector (when a Timeline
    /// was built via Ygg > Build Timeline) or samples the baked
    /// AnimationClip directly, and fires Spine AnimationState cues by
    /// reflection so the script compiles without spine-unity installed.
    /// </summary>
    public class YggScenePlayer : MonoBehaviour
    {
        public PlayableDirector director;
        public AnimationClip transformClip;
        public TextAsset descriptor;
        public float durationSeconds = 5f;
        public List<SpineCue> spineCues = new List<SpineCue>();
        /// Set by the Timeline builder once Spine Timeline tracks exist —
        /// the runtime cue fallback then steps aside to avoid double-firing.
        public bool spineCuesHandledByTimeline;

        bool playing;
        float elapsed;
        readonly HashSet<int> fired = new HashSet<int>();

        public bool IsPlaying => playing || (director != null && director.playableAsset != null && director.state == PlayState.Playing);

        void Start()
        {
            if (descriptor == null) return;
            DescriptorSpinCues desc;
            try { desc = JsonUtility.FromJson<DescriptorSpinCues>(descriptor.text); } catch { return; }
            if (desc?.spinnerCues == null) return;
            foreach (var cue in desc.spinnerCues)
            {
                var child = string.IsNullOrEmpty(cue.target) ? transform : transform.Find(cue.target);
                if (child == null) { Debug.LogWarning($"[YggScenePlayer] spinner target not found: {cue.target}"); continue; }
                var spinner = child.GetComponent<YggSpinner>();
                if (spinner == null) spinner = child.gameObject.AddComponent<YggSpinner>();
                // Newer prefabs ship the spinner pre-configured (serialized
                // configJson + bindings) — only configure legacy placeholders.
                if (!spinner.IsConfigured) spinner.Configure(cue.configJson, cue.clips);
            }
        }

        // Used only to extract spinnerCues from the descriptor JSON; all other
        // descriptor fields are intentionally ignored by JsonUtility.
        [Serializable] class DescriptorSpinCues { public SpinnerCueEntry[] spinnerCues; }
        [Serializable] class SpinnerCueEntry { public string target, configJson; public SpinnerClipData[] clips; }

        public void Play()
        {
            StopInternal();
            fired.Clear();
            elapsed = 0f;
            if (director != null && director.playableAsset != null)
            {
                director.time = 0;
                director.Play();
            }
            playing = true;
        }

        public void Stop()
        {
            StopInternal();
            if (transformClip != null) transformClip.SampleAnimation(gameObject, 0f);
        }

        void StopInternal()
        {
            playing = false;
            if (director != null && director.playableAsset != null) director.Stop();
        }

        void Update()
        {
            if (!playing) return;
            bool directorDriven = director != null && director.playableAsset != null;
            float t = directorDriven ? (float)director.time : elapsed;

            if (!directorDriven)
            {
                elapsed += Time.deltaTime;
                if (transformClip != null) transformClip.SampleAnimation(gameObject, Mathf.Min(t, transformClip.length));
            }

            if (!(directorDriven && spineCuesHandledByTimeline))
            {
                for (int i = 0; i < spineCues.Count; i++)
                {
                    if (fired.Contains(i)) continue;
                    var cue = spineCues[i];
                    if (t + 1e-4f < cue.start) continue;
                    fired.Add(i);
                    FireSpineCue(cue);
                }
            }

            foreach (var spinner in GetComponentsInChildren<YggSpinner>())
                spinner.Evaluate(t);

            if (t >= durationSeconds && !directorDriven) playing = false;
            if (directorDriven && director.state != PlayState.Playing && t > 0) playing = false;
        }

        void FireSpineCue(SpineCue cue)
        {
            var child = string.IsNullOrEmpty(cue.target) ? transform : transform.Find(cue.target);
            if (child == null) { Debug.LogWarning($"[YggScenePlayer] spine cue target not found: {cue.target}"); return; }
            foreach (var comp in child.GetComponents<MonoBehaviour>())
            {
                if (comp == null) continue;
                var type = comp.GetType();
                if (type.FullName != "Spine.Unity.SkeletonGraphic" && type.FullName != "Spine.Unity.SkeletonAnimation") continue;
                var stateProp = type.GetProperty("AnimationState", BindingFlags.Public | BindingFlags.Instance);
                var state = stateProp != null ? stateProp.GetValue(comp) : null;
                if (state == null) { Debug.LogWarning($"[YggScenePlayer] {type.Name} on {child.name} has no AnimationState (SkeletonDataAsset assigned?)"); return; }
                var setAnim = state.GetType().GetMethod("SetAnimation", new[] { typeof(int), typeof(string), typeof(bool) });
                if (setAnim == null) return;
                var entry = setAnim.Invoke(state, new object[] { cue.trackIndex, cue.animationName, cue.loop });
                if (entry != null)
                {
                    var entryType = entry.GetType();
                    if (cue.mixDuration >= 0f)
                        entryType.GetProperty("MixDuration")?.SetValue(entry, cue.mixDuration);
                    if (Math.Abs(cue.speed - 1f) > 1e-4f)
                        entryType.GetProperty("TimeScale")?.SetValue(entry, cue.speed);
                }
                return;
            }
            Debug.LogWarning($"[YggScenePlayer] no Spine component on {child.name} — attach SkeletonGraphic/SkeletonAnimation and assign its SkeletonDataAsset.");
        }
    }
}
`;
}

/**
 * Auto-wiring of exported spine placeholders. Runs on package import (and
 * once per editor session, covering the very first import while these
 * scripts were still compiling), creating the spine components and saving
 * the SkeletonDataAsset references back into the prefab asset.
 */
export function spineAutoWireSource() {
  return `// Auto-generated by YGG Toolkit Scene Studio.
using System;
using System.Collections.Generic;
using System.IO;
using UnityEditor;
using UnityEngine;

namespace Ygg.SceneStudio
{
    public static class YggSpineAutoWire
    {
        [Serializable] public class DescriptorNode
        {
            public string path;
            public string kind;
            public string spineData;
            public string spineSkin;
            public string spineAnim;
            public bool spineLoop = true;
        }
        [Serializable] public class Descriptor { public string variant; public List<DescriptorNode> nodes; }

        /// <summary>
        /// Create-or-find the spine component on every exported spine node and
        /// assign SkeletonDataAsset/skin/animation from the descriptor.
        /// Returns the number of CHANGES applied (0 = already fully wired);
        /// unresolved counts nodes that could not be wired yet.
        /// </summary>
        public static int Wire(YggScenePlayer player, out int unresolved, bool interactive = true)
        {
            unresolved = 0;
            if (player == null || player.descriptor == null)
            {
                if (interactive) Debug.LogWarning("[Ygg] No descriptor TextAsset on the player — cannot auto-wire spine.");
                return 0;
            }
            Descriptor desc;
            try { desc = JsonUtility.FromJson<Descriptor>(player.descriptor.text); }
            catch (Exception e) { Debug.LogError("[Ygg] Failed to parse descriptor: " + e.Message); return 0; }
            if (desc?.nodes == null) return 0;

            var dataAssets = new List<(string name, string path)>();
            foreach (var guid in AssetDatabase.FindAssets("t:SkeletonDataAsset"))
            {
                var p = AssetDatabase.GUIDToAssetPath(guid);
                dataAssets.Add((Path.GetFileNameWithoutExtension(p), p));
            }

            int changes = 0;
            foreach (var node in desc.nodes)
            {
                if (string.IsNullOrEmpty(node.spineData)) continue;
                var child = string.IsNullOrEmpty(node.path) ? player.transform : player.transform.Find(node.path);
                if (child == null) { Debug.LogWarning($"[Ygg] spine node not found: {node.path}"); unresolved++; continue; }

                MonoBehaviour spineComp = null;
                foreach (var comp in child.GetComponents<MonoBehaviour>())
                {
                    if (comp == null) continue;
                    var fn = comp.GetType().FullName;
                    if (fn == "Spine.Unity.SkeletonGraphic" || fn == "Spine.Unity.SkeletonAnimation") { spineComp = comp; break; }
                }
                if (spineComp == null)
                {
                    string wantedType = desc.variant == "world"
                        ? "Spine.Unity.SkeletonAnimation, spine-unity"
                        : "Spine.Unity.SkeletonGraphic, spine-unity";
                    var t = Type.GetType(wantedType);
                    if (t == null)
                    {
                        if (interactive) Debug.LogWarning($"[Ygg] spine-unity runtime not found ({wantedType}) — cannot create component for {node.path}.");
                        unresolved++;
                        continue;
                    }
                    // AddComponent runs spine-unity's own editor defaults —
                    // materials auto-detected exactly like adding it by hand.
                    spineComp = interactive
                        ? (MonoBehaviour)Undo.AddComponent(child.gameObject, t)
                        : (MonoBehaviour)child.gameObject.AddComponent(t);
                    Debug.Log($"[Ygg] {node.path}: added {t.Name}", spineComp);
                    changes++;
                }

                var so = new SerializedObject(spineComp);
                var dataProp = so.FindProperty("skeletonDataAsset");
                if (dataProp == null) { unresolved++; continue; }

                if (dataProp.objectReferenceValue == null)
                {
                    string want = node.spineData + "_SkeletonData";
                    string found = null;
                    foreach (var (name, p) in dataAssets)
                    {
                        if (string.Equals(name, want, StringComparison.OrdinalIgnoreCase)) { found = p; break; }
                        if (found == null && name.StartsWith(node.spineData, StringComparison.OrdinalIgnoreCase)) found = p;
                    }
                    if (found == null)
                    {
                        if (interactive) Debug.LogWarning($"[Ygg] No SkeletonDataAsset found for '{node.spineData}' — has spine-unity imported the skeleton yet?");
                        unresolved++;
                        continue;
                    }
                    dataProp.objectReferenceValue = AssetDatabase.LoadAssetAtPath<UnityEngine.Object>(found);
                    Debug.Log($"[Ygg] {node.path} \\u2190 {found}", spineComp);
                }

                SetString(so, "initialSkinName", string.IsNullOrEmpty(node.spineSkin) ? "default" : node.spineSkin);
                SetString(so, "startingAnimation", node.spineAnim);   // SkeletonGraphic
                SetString(so, "_animationName", node.spineAnim);      // SkeletonAnimation
                SetBool(so, "startingLoop", node.spineLoop);
                SetBool(so, "loop", node.spineLoop);
                if (so.ApplyModifiedProperties()) changes++;
                EditorUtility.SetDirty(spineComp);
            }
            if (interactive) Debug.Log($"[Ygg] Spine auto-wire done: {changes} change(s), {unresolved} unresolved.");
            return changes;
        }

        /// <summary>
        /// Open a prefab asset, wire it, and save it back when changed.
        /// Returns true when fully resolved (no retry needed).
        /// </summary>
        public static bool WirePrefabAtPath(string prefabPath)
        {
            var root = PrefabUtility.LoadPrefabContents(prefabPath);
            try
            {
                var player = root.GetComponentInChildren<YggScenePlayer>();
                if (player == null) return true;
                int changes = Wire(player, out int unresolved, interactive: false);
                if (changes > 0)
                {
                    PrefabUtility.SaveAsPrefabAsset(root, prefabPath);
                    Debug.Log($"[Ygg] Auto-wired spine in {prefabPath} ({changes} change(s)).");
                }
                return unresolved == 0;
            }
            finally
            {
                PrefabUtility.UnloadPrefabContents(root);
            }
        }

        // ── automatic wiring on package import ────────────────────────────
        class ImportHook : AssetPostprocessor
        {
            static void OnPostprocessAllAssets(string[] imported, string[] deleted, string[] moved, string[] movedFrom)
            {
                var prefabs = new List<string>();
                foreach (var p in imported)
                    if (p.EndsWith(".prefab", StringComparison.OrdinalIgnoreCase)) prefabs.Add(p);
                if (prefabs.Count > 0) SchedulePrefabWiring(prefabs, 8);
            }
        }

        static void SchedulePrefabWiring(List<string> prefabPaths, int retries)
        {
            EditorApplication.delayCall += () =>
            {
                if (EditorApplication.isCompiling || EditorApplication.isUpdating)
                {
                    if (retries > 0) SchedulePrefabWiring(prefabPaths, retries - 1);
                    return;
                }
                var remaining = new List<string>();
                foreach (var path in prefabPaths)
                {
                    var go = AssetDatabase.LoadAssetAtPath<GameObject>(path);
                    if (go == null || go.GetComponentInChildren<YggScenePlayer>() == null) continue;
                    bool complete;
                    try { complete = WirePrefabAtPath(path); }
                    catch (Exception e) { Debug.LogWarning($"[Ygg] auto-wire failed for {path}: {e.Message}"); continue; }
                    // SkeletonDataAssets may not be generated yet on the first
                    // pass — retry on later editor ticks.
                    if (!complete) remaining.Add(path);
                }
                if (remaining.Count > 0 && retries > 0) SchedulePrefabWiring(remaining, retries - 1);
            };
        }

        // Once per session: covers the very first package import, when these
        // scripts were still compiling while the prefab was imported.
        [InitializeOnLoadMethod]
        static void SessionSweep()
        {
            if (SessionState.GetBool("Ygg.AutoWire.Swept", false)) return;
            SessionState.SetBool("Ygg.AutoWire.Swept", true);
            EditorApplication.delayCall += () =>
            {
                var prefabs = new List<string>();
                foreach (var guid in AssetDatabase.FindAssets("_timeline t:TextAsset"))
                {
                    var descPath = AssetDatabase.GUIDToAssetPath(guid);
                    var dir = Path.GetDirectoryName(descPath);
                    if (string.IsNullOrEmpty(dir)) continue;
                    foreach (var pguid in AssetDatabase.FindAssets("t:Prefab", new[] { dir.Replace('\\\\', '/') }))
                    {
                        var p = AssetDatabase.GUIDToAssetPath(pguid);
                        if (!prefabs.Contains(p)) prefabs.Add(p);
                    }
                }
                if (prefabs.Count > 0) SchedulePrefabWiring(prefabs, 2);
            };
        }

        static void SetString(SerializedObject so, string prop, string value)
        {
            var p = so.FindProperty(prop);
            if (p != null && value != null && p.stringValue != value) p.stringValue = value;
        }

        static void SetBool(SerializedObject so, string prop, bool value)
        {
            var p = so.FindProperty(prop);
            if (p != null && p.boolValue != value) p.boolValue = value;
        }
    }
}
`;
}

export function scenePlayerEditorSource() {
  return `// Auto-generated by YGG Toolkit Scene Studio.
using System;
using System.Reflection;
using UnityEditor;
using UnityEngine;

namespace Ygg.SceneStudio
{
    [CustomEditor(typeof(YggScenePlayer))]
    // Fully qualified base class: projects with a DLL exposing a root-level
    // "Editor" namespace would otherwise shadow UnityEditor.Editor (CS0118).
    public class YggScenePlayerEditor : UnityEditor.Editor
    {
        // The builder lives in Ygg.SceneStudio.Editor.Timeline, which only
        // compiles when com.unity.timeline is installed — resolve it
        // reflectively so this assembly never references it directly.
        static MethodInfo TimelineBuild =>
            Type.GetType("Ygg.SceneStudio.YggSceneTimelineBuilder, Ygg.SceneStudio.Editor.Timeline")
                ?.GetMethod("Build", new[] { typeof(YggScenePlayer) });

        public override void OnInspectorGUI()
        {
            DrawDefaultInspector();
            var player = (YggScenePlayer)target;

            EditorGUILayout.Space();
            if (GUILayout.Button("Auto-assign Spine Data"))
            {
                YggSpineAutoWire.Wire(player, out _);
            }
            var build = TimelineBuild;
            using (new EditorGUI.DisabledScope(build == null))
            {
                if (GUILayout.Button("Build Unity Timeline from baked clip"))
                    build.Invoke(null, new object[] { player });
            }
            if (build == null)
                EditorGUILayout.HelpBox("Unity Timeline package not installed - use Ygg > Scene Studio > Install Required Packages. \\u25B6 Play works without it (direct clip sampling).", MessageType.Info);

            using (new EditorGUI.DisabledScope(!Application.isPlaying))
            {
                EditorGUILayout.BeginHorizontal();
                if (GUILayout.Button("▶ Play")) player.Play();
                if (GUILayout.Button("■ Stop")) player.Stop();
                EditorGUILayout.EndHorizontal();
            }
            if (!Application.isPlaying)
                EditorGUILayout.HelpBox("Spine components are wired automatically on import; the buttons re-run wiring and (re)build the Timeline. Enter Play Mode to use Play/Stop.", MessageType.Info);
        }
    }
}
`;
}

export function timelineBuilderSource() {
  return `// Auto-generated by YGG Toolkit Scene Studio.
//
// Builds a Unity TimelineAsset from the baked AnimationClip + spine cues
// using the official Timeline API — no fragile serialized Timeline YAML.
// With the spine-timeline extension installed, spine cues become REAL
// Spine Animation State tracks/clips (AnimationReferenceAssets are created
// as needed); otherwise the cues stay on YggScenePlayer as a runtime
// fallback.
//
// This file lives in the Ygg.SceneStudio.Editor.Timeline assembly, which is
// excluded from compilation entirely (defineConstraints) when the
// com.unity.timeline package is missing — importing the package never
// breaks the project; ▶ Play then samples the baked clip directly.
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using UnityEditor;
using UnityEngine;
using UnityEngine.Playables;
using UnityEngine.Timeline;

namespace Ygg.SceneStudio
{
    public static class YggSceneTimelineBuilder
    {
        public static void Build(YggScenePlayer player)
        {
            if (player == null) return;
            var director = player.director != null ? player.director : player.GetComponent<PlayableDirector>();
            if (director == null) { Debug.LogError("[Ygg] No PlayableDirector on the scene player."); return; }

            string basePath = GetAssetFolder(player);
            string assetPath = Path.Combine(basePath, player.gameObject.name + "_Timeline.playable").Replace('\\\\', '/');

            var timeline = AssetDatabase.LoadAssetAtPath<TimelineAsset>(assetPath);
            if (timeline == null)
            {
                timeline = ScriptableObject.CreateInstance<TimelineAsset>();
                AssetDatabase.CreateAsset(timeline, assetPath);
            }
            else
            {
                foreach (var t in timeline.GetRootTracks().ToList())
                    timeline.DeleteTrack(t);
            }

            timeline.fixedDuration = player.durationSeconds;
            timeline.durationMode = TimelineAsset.DurationMode.FixedLength;

            if (player.transformClip != null)
            {
                var track = timeline.CreateTrack<AnimationTrack>(null, "Baked transforms");
                var clip = track.CreateClip(player.transformClip);
                clip.start = 0;
                clip.duration = Math.Max(0.05f, player.transformClip.length);
                var animator = player.GetComponent<Animator>();
                if (animator != null) director.SetGenericBinding(track, animator);
            }

            TryBuildSpineTracks(player, timeline, director, basePath.Replace('\\\\', '/'));

            director.playableAsset = timeline;
            EditorUtility.SetDirty(timeline);
            EditorUtility.SetDirty(director);
            EditorUtility.SetDirty(player);
            AssetDatabase.SaveAssets();
            Debug.Log($"[Ygg] Timeline built at {assetPath}", timeline);
        }

        static string GetAssetFolder(YggScenePlayer player)
        {
            // Next to the prefab when the player comes from one, else the clip's folder.
            string src = null;
            var prefab = PrefabUtility.GetCorrespondingObjectFromSource(player.gameObject);
            if (prefab != null) src = AssetDatabase.GetAssetPath(prefab);
            if (string.IsNullOrEmpty(src) && player.transformClip != null) src = AssetDatabase.GetAssetPath(player.transformClip);
            if (string.IsNullOrEmpty(src)) src = "Assets";
            return Path.GetDirectoryName(src);
        }

        static void TryBuildSpineTracks(YggScenePlayer player, TimelineAsset timeline, PlayableDirector director, string assetFolder)
        {
            if (player.spineCues == null || player.spineCues.Count == 0) return;

            var graphicTrackType = Type.GetType("Spine.Unity.Playables.SpineAnimationStateGraphicTrack, spine-timeline");
            var animTrackType = Type.GetType("Spine.Unity.Playables.SpineAnimationStateTrack, spine-timeline");
            var clipType = Type.GetType("Spine.Unity.Playables.SpineAnimationStateClip, spine-timeline");
            var refAssetType = Type.GetType("Spine.Unity.AnimationReferenceAsset, spine-unity");
            if (clipType == null || refAssetType == null || (graphicTrackType == null && animTrackType == null))
            {
                Debug.Log("[Ygg] spine-timeline extension not found — spine cues stay on YggScenePlayer (runtime fallback). Install it via the Ygg bootstrap dialog or Package Manager.");
                player.spineCuesHandledByTimeline = false;
                return;
            }

            var createClip = typeof(TrackAsset).GetMethods(BindingFlags.Public | BindingFlags.Instance)
                .First(m => m.Name == "CreateClip" && m.IsGenericMethod && m.GetParameters().Length == 0)
                .MakeGenericMethod(clipType);

            string refFolder = assetFolder + "/SpineRefs";
            if (!AssetDatabase.IsValidFolder(refFolder))
                AssetDatabase.CreateFolder(assetFolder, "SpineRefs");

            // One track per (target, spine track index), clips in cue order.
            var groups = new Dictionary<string, List<SpineCue>>();
            foreach (var cue in player.spineCues)
            {
                string key = cue.target + "\\u0001" + cue.trackIndex;
                if (!groups.TryGetValue(key, out var list)) groups[key] = list = new List<SpineCue>();
                list.Add(cue);
            }

            int built = 0;
            foreach (var group in groups.Values)
            {
                var first = group[0];
                var child = string.IsNullOrEmpty(first.target) ? player.transform : player.transform.Find(first.target);
                if (child == null) { Debug.LogWarning($"[Ygg] spine cue target not found: {first.target}"); continue; }

                MonoBehaviour spineComp = null;
                bool isGraphic = false;
                foreach (var comp in child.GetComponents<MonoBehaviour>())
                {
                    if (comp == null) continue;
                    var fn = comp.GetType().FullName;
                    if (fn == "Spine.Unity.SkeletonGraphic") { spineComp = comp; isGraphic = true; break; }
                    if (fn == "Spine.Unity.SkeletonAnimation") { spineComp = comp; break; }
                }
                if (spineComp == null) { Debug.LogWarning($"[Ygg] no spine component on {first.target} — run Auto-assign Spine Data first."); continue; }

                var dataAsset = new SerializedObject(spineComp).FindProperty("skeletonDataAsset")?.objectReferenceValue;
                if (dataAsset == null) { Debug.LogWarning($"[Ygg] {first.target}: SkeletonDataAsset not assigned — run Auto-assign Spine Data first."); continue; }

                var trackType = isGraphic ? (graphicTrackType ?? animTrackType) : (animTrackType ?? graphicTrackType);
                var track = timeline.CreateTrack(trackType, null, "Spine: " + first.target);
                var soTrack = new SerializedObject(track);
                var tiProp = soTrack.FindProperty("trackIndex");
                if (tiProp != null) { tiProp.intValue = first.trackIndex; soTrack.ApplyModifiedProperties(); }
                director.SetGenericBinding(track, spineComp);

                foreach (var cue in group.OrderBy(c => c.start))
                {
                    var refAsset = EnsureReferenceAsset(refFolder, dataAsset, cue.animationName, refAssetType);
                    var clip = (TimelineClip)createClip.Invoke(track, null);
                    clip.start = cue.start;
                    clip.duration = Math.Max(0.05, cue.duration);
                    clip.displayName = cue.animationName;
                    if (Math.Abs(cue.speed - 1f) > 1e-4f) clip.timeScale = cue.speed;

                    var soClip = new SerializedObject(clip.asset);
                    SetRef(soClip, "template.animationReference", refAsset);
                    SetBool(soClip, "template.loop", cue.loop);
                    if (cue.mixDuration >= 0f)
                    {
                        SetFloat(soClip, "template.mixDuration", cue.mixDuration);
                        SetBool(soClip, "template.useBlendDuration", false);
                    }
                    soClip.ApplyModifiedProperties();
                }
                built++;
            }

            player.spineCuesHandledByTimeline = built > 0;
            if (built > 0) Debug.Log($"[Ygg] Built {built} Spine Timeline track(s); runtime cues disabled while the director drives playback.");
        }

        /// AnimationReferenceAssets are how Spine Timeline clips reference an
        /// animation — created on demand next to the timeline, reused after.
        static UnityEngine.Object EnsureReferenceAsset(string folder, UnityEngine.Object dataAsset, string animationName, Type refAssetType)
        {
            string safe = string.Concat(animationName.Select(ch => char.IsLetterOrDigit(ch) || ch == '_' || ch == '-' ? ch : '_'));
            string path = folder + "/" + dataAsset.name.Replace("_SkeletonData", "") + "_" + safe + ".asset";
            var existing = AssetDatabase.LoadAssetAtPath<UnityEngine.Object>(path);
            if (existing != null) return existing;

            var asset = ScriptableObject.CreateInstance(refAssetType);
            var so = new SerializedObject(asset);
            var animProp = so.FindProperty("animationName");
            if (animProp != null) animProp.stringValue = animationName;
            SetRef(so, "skeletonDataAsset", dataAsset);
            so.ApplyModifiedProperties();
            AssetDatabase.CreateAsset(asset, path);
            return asset;
        }

        static void SetRef(SerializedObject so, string prop, UnityEngine.Object value)
        {
            var p = so.FindProperty(prop);
            if (p != null) p.objectReferenceValue = value;
        }

        static void SetBool(SerializedObject so, string prop, bool value)
        {
            var p = so.FindProperty(prop);
            if (p != null) p.boolValue = value;
        }

        static void SetFloat(SerializedObject so, string prop, float value)
        {
            var p = so.FindProperty(prop);
            if (p != null) p.floatValue = value;
        }
    }

    /// <summary>
    /// Builds Timelines automatically: once per session on load (covers the
    /// first compile of this assembly — i.e. right after com.unity.timeline
    /// is installed) and for every imported Ygg prefab afterwards. Retries a
    /// few editor ticks so spine auto-wiring can finish first.
    /// </summary>
    static class YggTimelineAutoBuild
    {
        class ImportHook : AssetPostprocessor
        {
            static void OnPostprocessAllAssets(string[] imported, string[] deleted, string[] moved, string[] movedFrom)
            {
                var prefabs = new List<string>();
                foreach (var p in imported)
                    if (p.EndsWith(".prefab", StringComparison.OrdinalIgnoreCase)) prefabs.Add(p);
                if (prefabs.Count > 0) Schedule(prefabs, 8);
            }
        }

        [InitializeOnLoadMethod]
        static void SessionSweep()
        {
            if (SessionState.GetBool("Ygg.Timeline.AutoBuilt", false)) return;
            SessionState.SetBool("Ygg.Timeline.AutoBuilt", true);
            EditorApplication.delayCall += () =>
            {
                var prefabs = new List<string>();
                foreach (var guid in AssetDatabase.FindAssets("t:Prefab"))
                {
                    var path = AssetDatabase.GUIDToAssetPath(guid);
                    if (path.StartsWith("Assets/")) prefabs.Add(path);
                }
                Schedule(prefabs, 8);
            };
        }

        static void Schedule(List<string> prefabPaths, int retries)
        {
            EditorApplication.delayCall += () =>
            {
                if (EditorApplication.isCompiling || EditorApplication.isUpdating)
                {
                    if (retries > 0) Schedule(prefabPaths, retries - 1);
                    return;
                }
                var remaining = new List<string>();
                foreach (var path in prefabPaths)
                {
                    var go = AssetDatabase.LoadAssetAtPath<GameObject>(path);
                    var player = go != null ? go.GetComponentInChildren<YggScenePlayer>() : null;
                    if (player == null) continue;
                    var director = player.director != null ? player.director : player.GetComponent<PlayableDirector>();
                    if (director == null || director.playableAsset != null) continue;
                    // Spine cues need wired SkeletonDataAssets for real Spine
                    // tracks — wait for YggSpineAutoWire when they're missing.
                    if (player.spineCues != null && player.spineCues.Count > 0 && !SpineWired(player))
                    {
                        remaining.Add(path);
                        continue;
                    }
                    try { BuildForPrefab(path); }
                    catch (Exception e) { Debug.LogWarning($"[Ygg] Timeline auto-build failed for {path}: {e.Message}"); }
                }
                if (remaining.Count > 0 && retries > 0) Schedule(remaining, retries - 1);
            };
        }

        static bool SpineWired(YggScenePlayer player)
        {
            foreach (var cue in player.spineCues)
            {
                var child = string.IsNullOrEmpty(cue.target) ? player.transform : player.transform.Find(cue.target);
                if (child == null) continue;
                foreach (var comp in child.GetComponents<MonoBehaviour>())
                {
                    if (comp == null) continue;
                    var fn = comp.GetType().FullName;
                    if (fn != "Spine.Unity.SkeletonGraphic" && fn != "Spine.Unity.SkeletonAnimation") continue;
                    var data = new SerializedObject(comp).FindProperty("skeletonDataAsset")?.objectReferenceValue;
                    if (data == null) return false;
                }
            }
            return true;
        }

        static void BuildForPrefab(string path)
        {
            var root = PrefabUtility.LoadPrefabContents(path);
            try
            {
                var player = root.GetComponentInChildren<YggScenePlayer>();
                if (player == null) return;
                YggSceneTimelineBuilder.Build(player);
                PrefabUtility.SaveAsPrefabAsset(root, path);
                Debug.Log($"[Ygg] Timeline auto-built for {path}");
            }
            finally
            {
                PrefabUtility.UnloadPrefabContents(root);
            }
        }
    }
}
`;
}

/**
 * YggSpinner -- direct C# port of spinnerEval.js.
 *
 * Data model uses SpinnerRow wrappers (JsonUtility does not support string[][]).
 * Symbol sprites are bound via SpinnerSymbolBinding[] assigned in the Inspector.
 */
export function spinnerSource() {
  return `// Auto-generated by YGG Toolkit Scene Studio.
// All nested string arrays use SpinnerRow so Unity JsonUtility can deserialise them.
using System;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

namespace Ygg.SceneStudio
{
    [Serializable] public class SpinnerRow { public string[] cells; }

    [Serializable]
    public class SpinnerSymbolData { public string id, name, assetId, blurAssetId; }

    [Serializable]
    public class SpinnerConfigData
    {
        public SpinnerSymbolData[] symbols;
        public int reels = 5, rows = 3;
        public float cellW = 200, cellH = 200, spacingX = 0, spacingY = 0;
        public int direction = 1;
        public SpinnerRow[] strips;
        public SpinnerRow[] initialBoard;
        public float startDuration = 0.4f, spinSpeed = 12f, stopDuration = 0.6f;
        public float reelStaggerStart = 0.08f, reelStaggerStop = 0.15f;
        public string startEase = "easeIn", stopEase = "easeOut";
        public string bounceCurve = "backOut";
        public float bounceAmplitude = 0.35f, bounceDurationFrac = 0.35f;
        public bool blurEnabled = true;
        public float blurVLo = 4f, blurVHi = 9f;
        public float winDelay = 0.15f, landAnimDuration = 0.5f, winAnimDuration = 1f;
    }

    [Serializable]
    public class SpinnerClipData
    {
        public string action;
        public float start, duration;
        public SpinnerRow[] targetBoard;
        public bool matchEntrySpeed = true;
        public float[] perReelStartDelay, perReelStopDelay;

        public string[][] GetBoard()
        {
            if (targetBoard == null) return null;
            var b = new string[targetBoard.Length][];
            for (int r = 0; r < targetBoard.Length; r++)
                b[r] = targetBoard[r]?.cells ?? Array.Empty<string>();
            return b;
        }
    }

    [Serializable]
    public class SpinnerSymbolBinding
    {
        public string symbolId;
        public Sprite staticSprite, blurSprite;
    }

    [Serializable] class SpinnerClipList { public SpinnerClipData[] clips; }

    public class YggSpinner : MonoBehaviour
    {
        // Serialized by the exporter directly into the prefab — the component
        // self-configures on Awake, no YggScenePlayer needed for setup.
        [TextArea(2, 6)] public string configJson;
        [TextArea(2, 6)] public string clipsJson;
        public SpinnerSymbolBinding[] symbolBindings;
        // World variant renders SpriteRenderer cells masked by per-reel
        // SpriteMasks; positions are divided by pixelsPerUnit. The UI variant
        // ignores all three fields.
        public bool worldVariant;
        public float pixelsPerUnit = 100f;
        public Sprite maskSprite;

        SpinnerConfigData _cfg;
        ResolvedTrack _resolved;
        bool _built;
        float _W, _H, _pitchY;
        Transform _fxRoot;

        struct CellView
        {
            public Transform sTr, bTr;
            public Image staticImg, blurImg;        // ui
            public SpriteRenderer staticSr, blurSr; // world
            public string symId;
            public float fitS, fitB;                // world: sprite-to-cell fit scale
        }
        List<CellView>[] _reelCells;

        public bool IsConfigured => _cfg != null;
        /// Top render layer of the reel board — land/win FX parent.
        public Transform FxRoot => _fxRoot;

        public void Configure(string cfgJson, SpinnerClipData[] clips)
        {
            if (!string.IsNullOrEmpty(cfgJson))
                _cfg = JsonUtility.FromJson<SpinnerConfigData>(cfgJson);
            if (_cfg == null) return;
            _pitchY = _cfg.cellH + _cfg.spacingY;
            _W = _cfg.reels * _cfg.cellW + (_cfg.reels - 1) * _cfg.spacingX;
            _H = _cfg.rows  * _cfg.cellH + (_cfg.rows - 1)  * _cfg.spacingY;
            _resolved = ResolveTrack(_cfg, clips);
            if (!_built && !BindBakedHierarchy()) BuildRuntime();
            Evaluate(0f);
        }

        /// Configure from the serialized prefab fields (idempotent).
        public void EnsureConfigured()
        {
            if (_cfg != null || string.IsNullOrEmpty(configJson)) return;
            SpinnerClipData[] parsed = null;
            if (!string.IsNullOrEmpty(clipsJson))
            {
                try { parsed = JsonUtility.FromJson<SpinnerClipList>(clipsJson)?.clips; }
                catch (Exception e) { Debug.LogWarning("[YggSpinner] clipsJson parse failed: " + e.Message, this); }
            }
            Configure(configJson, parsed);
        }

        void Awake() { EnsureConfigured(); }

        public void Evaluate(float t)
        {
            if (_cfg == null || !_built) return;
            var res = EvaluateInternal(_cfg, _resolved, t);
            for (int r = 0; r < _cfg.reels; r++)
            {
                var reel = res[r];
                float disp = (reel.frac + reel.bounceOffset) * _cfg.direction;
                for (int i = 0; i < _reelCells[r].Count; i++)
                {
                    var cell = _reelCells[r][i];
                    var data = reel.cells[i];
                    float y = _H / 2f - _cfg.cellH / 2f - (data.gridRow + disp) * _pitchY;
                    SetCellY(cell.sTr, y);
                    SetCellY(cell.bTr, y);
                    if (cell.symId != data.symbolId)
                    {
                        var bind = FindBinding(data.symbolId);
                        if (bind != null)
                        {
                            var blur = bind.blurSprite != null ? bind.blurSprite : bind.staticSprite;
                            if (worldVariant)
                            {
                                if (cell.staticSr != null) cell.staticSr.sprite = bind.staticSprite;
                                if (cell.blurSr != null) cell.blurSr.sprite = blur;
                                cell.fitS = FitScale(bind.staticSprite);
                                cell.fitB = FitScale(blur);
                            }
                            else
                            {
                                if (cell.staticImg != null) cell.staticImg.sprite = bind.staticSprite;
                                if (cell.blurImg != null) cell.blurImg.sprite = blur;
                            }
                        }
                        cell.symId = data.symbolId;
                    }
                    var sCol = new Color(1, 1, 1, 1f - reel.blurMix);
                    var bCol = new Color(1, 1, 1, reel.blurMix);
                    if (worldVariant)
                    {
                        if (cell.staticSr != null) cell.staticSr.color = sCol;
                        if (cell.blurSr != null) cell.blurSr.color = bCol;
                    }
                    else
                    {
                        if (cell.staticImg != null) cell.staticImg.color = sCol;
                        if (cell.blurImg != null) cell.blurImg.color = bCol;
                    }
                    float punch = 1f;
                    if (data.state == CellState.Landing) {
                        float p = Mathf.Min(1, data.stateT / _cfg.landAnimDuration);
                        punch = 1 + 0.12f * Mathf.Sin(Mathf.PI * p);
                    } else if (data.state == CellState.Win) {
                        float p = Mathf.Min(1, data.stateT / _cfg.winAnimDuration);
                        punch = 1 + 0.18f * Mathf.Sin(Mathf.PI * Mathf.Min(1, p*2)) * (1 - p*0.5f);
                    }
                    cell.sTr.localScale = Vector3.one * ((worldVariant ? cell.fitS : 1f) * punch);
                    cell.bTr.localScale = Vector3.one * ((worldVariant ? cell.fitB : 1f) * punch);
                    _reelCells[r][i] = cell;
                }
            }
        }

        void SetCellY(Transform tr, float yPx)
        {
            var rt = tr as RectTransform;
            if (rt != null && !worldVariant) rt.anchoredPosition = new Vector2(rt.anchoredPosition.x, yPx);
            else tr.localPosition = new Vector3(tr.localPosition.x, yPx / Mathf.Max(1e-3f, pixelsPerUnit), 0);
        }

        float FitScale(Sprite s)
        {
            if (s == null) return 1f;
            return Mathf.Min(_cfg.cellW / Mathf.Max(1f, s.rect.width), _cfg.cellH / Mathf.Max(1f, s.rect.height));
        }

        SpinnerSymbolBinding FindBinding(string id)
        {
            if (symbolBindings == null) return null;
            foreach (var b in symbolBindings) if (b != null && b.symbolId == id) return b;
            return null;
        }

        // ── Hierarchy: bind the exporter-baked structure, or build it ─────
        //
        //   Board > Statics > Reel_r (mask) > Cell_-1..Cell_rows
        //         > Blurs   > Reel_r (mask) > Cell_-1..Cell_rows
        //         > Fx                                  (land/win renderers)
        //
        // Statics/Blurs are sibling layers (contiguous draw order batches;
        // per-cell nesting would interleave materials). Baked cells are the
        // pool's warm start: a config edit that needs more reels/rows spawns
        // extras at runtime; shrunk configs deactivate the leftovers.

        bool BindBakedHierarchy()
        {
            var board = transform.Find("Board");
            if (board == null) return false;
            var statics = board.Find("Statics");
            var blurs = board.Find("Blurs");
            if (statics == null || blurs == null) return false; // legacy prefab
            _fxRoot = board.Find("Fx");
            _reelCells = new List<CellView>[_cfg.reels];
            for (int r = 0; r < _cfg.reels; r++)
            {
                var sReel = EnsureReel(statics, r);
                var bReel = EnsureReel(blurs, r);
                _reelCells[r] = new List<CellView>();
                for (int j = -1; j <= _cfg.rows; j++)
                {
                    var v = new CellView
                    {
                        sTr = EnsureCell(sReel, j, false, 0),
                        bTr = EnsureCell(bReel, j, true, 1),
                        symId = null, fitS = 1f, fitB = 1f
                    };
                    v.staticImg = v.sTr.GetComponent<Image>();
                    v.blurImg = v.bTr.GetComponent<Image>();
                    v.staticSr = v.sTr.GetComponent<SpriteRenderer>();
                    v.blurSr = v.bTr.GetComponent<SpriteRenderer>();
                    _reelCells[r].Add(v);
                }
                HideExtraCells(sReel); HideExtraCells(bReel);
            }
            HideExtraReels(statics); HideExtraReels(blurs);
            _built = true;
            return true;
        }

        void BuildRuntime()
        {
            var board = NewContainer(transform, "Board");
            NewContainer(board, "Statics");
            NewContainer(board, "Blurs");
            NewContainer(board, "Fx");
            BindBakedHierarchy();
        }

        Transform NewContainer(Transform parent, string name)
        {
            var go = new GameObject(name);
            go.transform.SetParent(parent, false);
            if (!worldVariant)
            {
                var rt = go.AddComponent<RectTransform>();
                rt.anchorMin = rt.anchorMax = rt.pivot = new Vector2(0.5f, 0.5f);
                rt.sizeDelta = new Vector2(_W, _H);
                rt.anchoredPosition = Vector2.zero;
            }
            return go.transform;
        }

        Transform EnsureReel(Transform parent, int r)
        {
            var tr = parent.Find("Reel_" + r);
            if (tr != null) { tr.gameObject.SetActive(true); return tr; }
            var go = new GameObject("Reel_" + r);
            go.transform.SetParent(parent, false);
            float colX = r * (_cfg.cellW + _cfg.spacingX) - _W / 2f + _cfg.cellW / 2f;
            if (!worldVariant)
            {
                var rt = go.AddComponent<RectTransform>();
                rt.anchorMin = rt.anchorMax = rt.pivot = new Vector2(0.5f, 0.5f);
                rt.sizeDelta = new Vector2(_cfg.cellW, _H);
                rt.anchoredPosition = new Vector2(colX, 0);
                go.AddComponent<RectMask2D>();
            }
            else
            {
                go.transform.localPosition = new Vector3(colX / Mathf.Max(1e-3f, pixelsPerUnit), 0, 0);
                if (maskSprite != null)
                {
                    var maskGo = new GameObject("Mask");
                    maskGo.transform.SetParent(go.transform, false);
                    var sm = maskGo.AddComponent<SpriteMask>();
                    sm.sprite = maskSprite;
                    maskGo.transform.localScale = new Vector3(
                        _cfg.cellW / Mathf.Max(1f, maskSprite.rect.width),
                        _H / Mathf.Max(1f, maskSprite.rect.height), 1);
                }
            }
            return go.transform;
        }

        Transform EnsureCell(Transform reel, int j, bool isBlur, int sortingOrder)
        {
            var tr = reel.Find("Cell_" + j);
            if (tr != null) { tr.gameObject.SetActive(true); return tr; }
            var go = new GameObject("Cell_" + j);
            go.transform.SetParent(reel, false);
            float y = _H / 2f - _cfg.cellH / 2f - j * _pitchY;
            if (!worldVariant)
            {
                var rt = go.AddComponent<RectTransform>();
                rt.anchorMin = rt.anchorMax = rt.pivot = new Vector2(0.5f, 0.5f);
                rt.sizeDelta = new Vector2(_cfg.cellW, _cfg.cellH);
                rt.anchoredPosition = new Vector2(0, y);
                var img = go.AddComponent<Image>();
                img.preserveAspect = true;
                img.raycastTarget = false;
                img.color = new Color(1, 1, 1, isBlur ? 0f : 1f);
            }
            else
            {
                go.transform.localPosition = new Vector3(0, y / Mathf.Max(1e-3f, pixelsPerUnit), 0);
                var sr = go.AddComponent<SpriteRenderer>();
                sr.maskInteraction = SpriteMaskInteraction.VisibleInsideMask;
                sr.sortingOrder = sortingOrder;
                sr.color = new Color(1, 1, 1, isBlur ? 0f : 1f);
            }
            return go.transform;
        }

        void HideExtraCells(Transform reel)
        {
            foreach (Transform c in reel)
            {
                if (!c.name.StartsWith("Cell_")) continue;
                int j;
                if (int.TryParse(c.name.Substring(5), out j) && (j < -1 || j > _cfg.rows))
                    c.gameObject.SetActive(false);
            }
        }

        void HideExtraReels(Transform layerRoot)
        {
            foreach (Transform c in layerRoot)
            {
                if (!c.name.StartsWith("Reel_")) continue;
                int r;
                if (int.TryParse(c.name.Substring(5), out r) && r >= _cfg.reels)
                    c.gameObject.SetActive(false);
            }
        }

        enum CellState { Idle, Spinning, Landing, Win }
        struct CellResult { public int gridRow; public string symbolId; public CellState state; public float stateT; }
        struct ReelResult  { public float frac, blurMix, bounceOffset; public CellResult[] cells; }
        struct Segment {
            public int kind;
            public float t0,s0,v0,v1,d,D,ds;
            public string ease,easePos,bounceCurve;
            public float bounceAmplitude,bounceDurationFrac;
        }
        struct StopInfo { public float[] landAt; public float winStartAt; public WinCell[] winCells; }
        struct WinCell  { public int reel,row; }
        class ResolvedTrack { public List<Segment>[] segments; public Dictionary<int,string>[] overlayAbs; public List<StopInfo> stops; }

        static readonly Dictionary<string,float[]> LutV=new Dictionary<string,float[]>();
        static readonly Dictionary<string,float[]> LutI=new Dictionary<string,float[]>();
        const int LUT_N=256;

        static float Curve(string name,float x){
            x=Mathf.Clamp01(x);
            switch(name){
                case "easeIn":    return x*x;
                case "easeOut":   {float q=1-x;return 1-q*q;}
                case "easeInOut": return x<0.5f?2*x*x:1-Mathf.Pow(-2*x+2,2)/2f;
                case "smoothstep":return x*x*(3-2*x);
                case "backIn":    return x*x*(2.70158f*x-1.70158f);
                case "backOut":   {float t2=x-1;return 1+t2*t2*(2.70158f*t2+1.70158f);}
                case "overshoot": {float t2=x-1;return 1+t2*t2*(3.3f*t2+2.3f);}
                default:          return x;
            }
        }
        static void EnsureLUT(string s){
            if(LutV.ContainsKey(s))return;
            var v=new float[LUT_N+1];var g=new float[LUT_N+1];
            for(int i=0;i<=LUT_N;i++)v[i]=Curve(s,(float)i/LUT_N);
            for(int i=1;i<=LUT_N;i++)g[i]=g[i-1]+(v[i-1]+v[i])*0.5f/LUT_N;
            LutV[s]=v;LutI[s]=g;
        }
        static float LL(float[] a,float p){float x=Mathf.Clamp01(p)*LUT_N;int i=Mathf.Min(LUT_N-1,(int)x);return a[i]+(x-i)*(a[i+1]-a[i]);}
        static float LV(string s,float p){EnsureLUT(s);return LL(LutV[s],p);}
        static float LInt(string s,float p){EnsureLUT(s);return LL(LutI[s],p);}
        static float LD(string s,float p){EnsureLUT(s);var v=LutV[s];int i=Mathf.Clamp((int)(Mathf.Clamp01(p)*LUT_N),0,LUT_N-1);return(v[i+1]-v[i])*LUT_N;}
        static float EntrySlope(string e){return Mathf.Max(0.25f,Mathf.Min(6f,LD(e,0)));}

        static (float s,float v,float b) EvalSeg(Segment seg,float t){
            float tau=t-seg.t0;
            if(seg.kind==0)return(seg.s0+seg.v0*tau,seg.v0,0);
            if(seg.kind==1){float p=Mathf.Min(1,tau/seg.d);return(seg.s0+seg.v0*tau+(seg.v1-seg.v0)*seg.d*LInt(seg.ease,p),seg.v0+(seg.v1-seg.v0)*LV(seg.ease,p),0);}
            float pp=Mathf.Min(1,tau/seg.ds),bounce=0;
            if(seg.bounceAmplitude>0){float pw=1-seg.bounceDurationFrac;if(pp>=pw){float q=(pp-pw)/seg.bounceDurationFrac;bounce=seg.bounceAmplitude*(Curve(seg.bounceCurve,q)-q);}}
            return(seg.s0+seg.D*LV(seg.easePos,pp),seg.D*LD(seg.easePos,pp)/seg.ds,bounce);
        }
        static Segment SegAt(List<Segment> sl,float t){for(int i=sl.Count-1;i>=0;i--)if(t>=sl[i].t0)return sl[i];return sl.Count>0?sl[0]:default;}
        static string StripAt(SpinnerConfigData cfg,ResolvedTrack res,int r,int idx){
            if(res.overlayAbs[r].TryGetValue(idx,out var ov))return ov;
            var cells=cfg.strips[r].cells;int L=cells.Length;return cells[((idx%L)+L)%L];
        }
        static ReelResult[] EvaluateInternal(SpinnerConfigData cfg,ResolvedTrack res,float t){
            int R=cfg.reels,rows=cfg.rows;var out2=new ReelResult[R];const float EPS=1e-6f;
            for(int r=0;r<R;r++){
                var seg=SegAt(res.segments[r],t);float s,v,bounce;(s,v,bounce)=EvalSeg(seg,t);
                int bi=Mathf.FloorToInt(s);float frac=s-bi,speed=Mathf.Abs(v);
                float bm=cfg.blurEnabled?Mathf.Clamp01((speed-cfg.blurVLo)/Mathf.Max(1e-6f,cfg.blurVHi-cfg.blurVLo)):0;
                StopInfo? stop=null;
                for(int i=res.stops.Count-1;i>=0;i--){if(res.stops[i].landAt[r]>=0&&t>=res.stops[i].landAt[r]){stop=res.stops[i];break;}}
                var cells=new CellResult[rows+2];
                for(int j=-1;j<=rows;j++){
                    int sr=cfg.direction==1?rows-1-j:j;string sid=StripAt(cfg,res,r,bi+sr);
                    var state=speed>EPS?CellState.Spinning:CellState.Idle;float stT=0;
                    if(speed<=EPS&&stop.HasValue&&j>=0&&j<rows){
                        var st=stop.Value;bool inWin=t>=st.winStartAt&&t<st.winStartAt+cfg.winAnimDuration&&Array.Exists(st.winCells,c=>c.reel==r&&c.row==j);
                        if(inWin){state=CellState.Win;stT=t-st.winStartAt;}
                        else if(t<st.landAt[r]+cfg.landAnimDuration){state=CellState.Landing;stT=t-st.landAt[r];}
                    }
                    cells[j+1]=new CellResult{gridRow=j,symbolId=sid,state=state,stateT=stT};
                }
                out2[r]=new ReelResult{frac=frac,blurMix=bm,bounceOffset=bounce,cells=cells};
            }
            return out2;
        }
        static ResolvedTrack ResolveTrack(SpinnerConfigData cfg,SpinnerClipData[] clips){
            int R=cfg.reels,rows=cfg.rows;
            var segs=new List<Segment>[R];var ov=new Dictionary<int,string>[R];
            for(int r=0;r<R;r++){segs[r]=new List<Segment>();ov[r]=new Dictionary<int,string>();}
            var st=new (float s,float v,float t)[R];
            int rowOff(int j)=>cfg.direction==1?rows-1-j:j;
            if(cfg.initialBoard!=null)
                for(int r=0;r<R;r++)
                    for(int j=0;j<rows;j++)
                        if(cfg.initialBoard[r]?.cells!=null&&j<cfg.initialBoard[r].cells.Length)
                            ov[r][rowOff(j)]=cfg.initialBoard[r].cells[j];
            var stops=new List<StopInfo>();
            var ordered=clips!=null?new List<SpinnerClipData>(clips):new List<SpinnerClipData>();
            ordered.Sort((a,b)=>a.start.CompareTo(b.start));
            foreach(var clip in ordered){
                float tA=clip.start,tB=clip.start+clip.duration;
                var landAt=new float[R];for(int r2=0;r2<R;r2++)landAt[r2]=-1;
                var target=clip.action=="stopSpin"?clip.GetBoard():null;
                for(int r=0;r<R;r++){
                    ref var s=ref st[r];
                    PushConst(segs[r],ref s,tA);
                    if(clip.action=="startSpin"){
                        float delay=clip.perReelStartDelay!=null&&r<clip.perReelStartDelay.Length?clip.perReelStartDelay[r]:r*cfg.reelStaggerStart;
                        PushConst(segs[r],ref s,tA+delay);
                        PushRamp(segs[r],ref s,Mathf.Min(tB,s.t+cfg.startDuration),cfg.spinSpeed,cfg.startDuration,cfg.startEase);
                        PushConst(segs[r],ref s,tB);
                    }else if(clip.action=="spin"){
                        if(Mathf.Abs(s.v-cfg.spinSpeed)>1e-6f){float fr=Mathf.Abs(1-s.v/cfg.spinSpeed);float dr=Mathf.Max(0.05f,cfg.startDuration*fr);PushRamp(segs[r],ref s,Mathf.Min(tB,s.t+dr),cfg.spinSpeed,dr,"easeInOut");}
                        PushConst(segs[r],ref s,tB);
                    }else if(clip.action=="stopSpin"){
                        float delay=clip.perReelStopDelay!=null&&r<clip.perReelStopDelay.Length?clip.perReelStopDelay[r]:r*cfg.reelStaggerStop;
                        PushConst(segs[r],ref s,tA+delay);
                        float v0=s.v;int minC=rows+2;float sFinal,dsEff;
                        if(v0<0.01f){sFinal=Mathf.Ceil(s.s)+minC;dsEff=cfg.stopDuration;}
                        else{float sl0=EntrySlope(cfg.stopEase);float dRaw=v0*cfg.stopDuration/sl0;sFinal=Mathf.Max(Mathf.Ceil(s.s+dRaw),Mathf.Ceil(s.s)+minC);dsEff=clip.matchEntrySpeed?(sFinal-s.s)*sl0/v0:cfg.stopDuration;}
                        PushDecel(segs[r],ref s,sFinal-s.s,dsEff,cfg.stopEase,cfg.bounceCurve,cfg.bounceAmplitude,cfg.bounceDurationFrac);
                        s.s=sFinal;
                        if(target!=null)for(int j=0;j<rows;j++)if(target[r]!=null&&j<target[r].Length)ov[r][(int)sFinal+rowOff(j)]=target[r][j];
                        landAt[r]=s.t;PushConst(segs[r],ref s,tB);
                    }else{s.v=0;PushConst(segs[r],ref s,tB);}
                }
                if(clip.action=="stopSpin"&&target!=null){
                    float allLand=float.NegativeInfinity;foreach(var la in landAt)if(la>allLand)allLand=la;
                    stops.Add(new StopInfo{landAt=landAt,winStartAt=allLand+cfg.winDelay,winCells=EvalWaysWins(target,R,rows)});
                }
            }
            for(int r=0;r<R;r++)PushConst(segs[r],ref st[r],float.PositiveInfinity);
            return new ResolvedTrack{segments=segs,overlayAbs=ov,stops=stops};
        }
        static void PushConst(List<Segment> sl,ref (float s,float v,float t) st,float tEnd)
        {if(!(tEnd>st.t))return;sl.Add(new Segment{kind=0,t0=st.t,s0=st.s,v0=st.v});if(!float.IsPositiveInfinity(tEnd)){st.s+=st.v*(tEnd-st.t);st.t=tEnd;}}
        static void PushRamp(List<Segment> sl,ref (float s,float v,float t) st,float tEnd,float v1,float d,string ease)
        {if(!(tEnd>st.t)||!(d>0))return;sl.Add(new Segment{kind=1,t0=st.t,s0=st.s,v0=st.v,v1=v1,d=d,ease=ease});float p=Mathf.Min(1,(tEnd-st.t)/d);st.s+=st.v*(tEnd-st.t)+(v1-st.v)*d*LInt(ease,p);st.v+=(v1-st.v)*LV(ease,p);st.t=tEnd;}
        static void PushDecel(List<Segment> sl,ref (float s,float v,float t) st,float D,float ds,string ep,string bc,float ba,float bdf)
        {sl.Add(new Segment{kind=2,t0=st.t,s0=st.s,v0=st.v,D=D,ds=ds,easePos=ep,bounceCurve=bc,bounceAmplitude=ba,bounceDurationFrac=bdf});st.s+=D;st.v=0;st.t+=ds;}

        const int WAYS_MIN=3;
        static WinCell[] EvalWaysWins(string[][] b,int R,int rows){
            if(b==null)return Array.Empty<WinCell>();
            var res=new List<WinCell>();var seen=new HashSet<string>();
            for(int r=0;r<R;r++)if(b[r]!=null)foreach(var s in b[r])seen.Add(s);
            foreach(var sym in seen){
                int streak=0;for(int r=0;r<R;r++){bool f=false;if(b[r]!=null)foreach(var s in b[r])if(s==sym){f=true;break;}if(f)streak++;else break;}
                if(streak<WAYS_MIN)continue;
                for(int r=0;r<streak;r++)if(b[r]!=null)for(int j=0;j<b[r].Length;j++)if(b[r][j]==sym)res.Add(new WinCell{reel=r,row=j});
            }
            return res.ToArray();
        }
    }
}
`;
}

