// Generated C# sources shipped inside the .unitypackage.
//
// Strategy: the prefab + baked AnimationClip are plain serialized assets, but
// the Unity *Timeline* asset is built in-editor by generated code through the
// official Timeline API (YggSceneTimelineBuilder). Hand-writing .playable
// YAML would hard-code Timeline package script GUIDs and break across
// versions; the builder is version-proof and can also create Spine Timeline
// tracks when the spine.timeline package is present.
//
// Script paths/GUIDs are constant across exports, so two exported scenes
// share one copy of the runtime instead of colliding.

export const SCRIPT_PATHS = {
  player: 'Assets/YggSceneStudio/Runtime/YggScenePlayer.cs',
  playerEditor: 'Assets/YggSceneStudio/Editor/YggScenePlayerEditor.cs',
  timelineBuilder: 'Assets/YggSceneStudio/Editor/YggSceneTimelineBuilder.cs',
  packageBootstrap: 'Assets/YggSceneStudio/Editor/YggPackageBootstrap.cs',
  runtimeAsmdef: 'Assets/YggSceneStudio/Runtime/Ygg.SceneStudio.Runtime.asmdef',
  editorAsmdef: 'Assets/YggSceneStudio/Editor/Ygg.SceneStudio.Editor.asmdef'
};

/**
 * .unitypackage files cannot declare UPM dependencies, so this editor
 * bootstrap detects a missing com.unity.timeline after import and offers a
 * one-click install through the Package Manager API.
 */
export function packageBootstrapSource() {
  return `// Auto-generated by YGG Toolkit Scene Studio.
using System;
using UnityEditor;
using UnityEditor.PackageManager;
using UnityEngine;

namespace Ygg.SceneStudio
{
    public static class YggPackageBootstrap
    {
        const string SessionKey = "Ygg.SceneStudio.TimelinePrompted";

        [InitializeOnLoadMethod]
        static void EnsureTimelinePackage()
        {
            // Type lives in the Unity.Timeline assembly only when the package is installed.
            var timelineType = Type.GetType("UnityEngine.Timeline.TimelineAsset, Unity.Timeline");
            if (timelineType != null) return;
            if (SessionState.GetBool(SessionKey, false)) return;
            SessionState.SetBool(SessionKey, true);

            EditorApplication.delayCall += () =>
            {
                bool install = EditorUtility.DisplayDialog(
                    "YGG Scene Studio",
                    "The exported scene uses Unity Timeline, but the com.unity.timeline package is not installed.\\n\\nInstall it now via the Package Manager?",
                    "Install", "Not now");
                if (!install)
                {
                    Debug.Log("[Ygg] Skipped Timeline install - \\u25B6 Play still works via direct clip sampling. Install com.unity.timeline later to build Timeline assets.");
                    return;
                }
                Client.Add("com.unity.timeline");
                Debug.Log("[Ygg] Installing com.unity.timeline via Package Manager\\u2026");
            };
        }
    }
}
`;
}

// Assembly definitions isolate the generated scripts from Assembly-CSharp
// (a compile error in either side can't break the other) and provide the
// YGG_HAS_TIMELINE define only when com.unity.timeline is installed —
// without it the Timeline builder compiles to a stub and ▶ Play falls back
// to direct clip sampling.
export function runtimeAsmdefSource() {
  return JSON.stringify({
    name: 'Ygg.SceneStudio.Runtime',
    rootNamespace: 'Ygg.SceneStudio',
    references: [],
    includePlatforms: [],
    excludePlatforms: [],
    allowUnsafeCode: false,
    overrideReferences: false,
    precompiledReferences: [],
    autoReferenced: true,
    defineConstraints: [],
    versionDefines: [],
    noEngineReferences: false
  }, null, 2);
}

export function editorAsmdefSource() {
  return JSON.stringify({
    name: 'Ygg.SceneStudio.Editor',
    rootNamespace: 'Ygg.SceneStudio',
    references: ['Ygg.SceneStudio.Runtime', 'Unity.Timeline'],
    includePlatforms: ['Editor'],
    excludePlatforms: [],
    allowUnsafeCode: false,
    overrideReferences: false,
    precompiledReferences: [],
    autoReferenced: true,
    defineConstraints: [],
    versionDefines: [
      { name: 'com.unity.timeline', expression: '', define: 'YGG_HAS_TIMELINE' }
    ],
    noEngineReferences: false
  }, null, 2);
}

export function scenePlayerSource() {
  return `// Auto-generated by YGG Toolkit Scene Studio. Safe to re-import; shared
// across exported scene packages.
using System;
using System.Collections.Generic;
using System.Reflection;
using UnityEngine;
using UnityEngine.Playables;

namespace Ygg.SceneStudio
{
    [Serializable]
    public class SpineCue
    {
        public string target;
        public string animationName;
        public float start;
        public float duration;
        public float speed = 1f;
        public bool loop = true;
        public float mixDuration = -1f;
        public int trackIndex;
    }

    /// <summary>
    /// Plays the exported scene: drives the PlayableDirector (when a Timeline
    /// was built via Ygg > Build Timeline) or samples the baked
    /// AnimationClip directly, and fires Spine AnimationState cues by
    /// reflection so the script compiles without spine-unity installed.
    /// </summary>
    public class YggScenePlayer : MonoBehaviour
    {
        public PlayableDirector director;
        public AnimationClip transformClip;
        public TextAsset descriptor;
        public float durationSeconds = 5f;
        public List<SpineCue> spineCues = new List<SpineCue>();

        bool playing;
        float elapsed;
        readonly HashSet<int> fired = new HashSet<int>();

        public bool IsPlaying => playing || (director != null && director.playableAsset != null && director.state == PlayState.Playing);

        public void Play()
        {
            StopInternal();
            fired.Clear();
            elapsed = 0f;
            if (director != null && director.playableAsset != null)
            {
                director.time = 0;
                director.Play();
            }
            playing = true;
        }

        public void Stop()
        {
            StopInternal();
            if (transformClip != null) transformClip.SampleAnimation(gameObject, 0f);
        }

        void StopInternal()
        {
            playing = false;
            if (director != null && director.playableAsset != null) director.Stop();
        }

        void Update()
        {
            if (!playing) return;
            bool directorDriven = director != null && director.playableAsset != null;
            float t = directorDriven ? (float)director.time : elapsed;

            if (!directorDriven)
            {
                elapsed += Time.deltaTime;
                if (transformClip != null) transformClip.SampleAnimation(gameObject, Mathf.Min(t, transformClip.length));
            }

            for (int i = 0; i < spineCues.Count; i++)
            {
                if (fired.Contains(i)) continue;
                var cue = spineCues[i];
                if (t + 1e-4f < cue.start) continue;
                fired.Add(i);
                FireSpineCue(cue);
            }

            if (t >= durationSeconds && !directorDriven) playing = false;
            if (directorDriven && director.state != PlayState.Playing && t > 0) playing = false;
        }

        void FireSpineCue(SpineCue cue)
        {
            var child = string.IsNullOrEmpty(cue.target) ? transform : transform.Find(cue.target);
            if (child == null) { Debug.LogWarning($"[YggScenePlayer] spine cue target not found: {cue.target}"); return; }
            foreach (var comp in child.GetComponents<MonoBehaviour>())
            {
                if (comp == null) continue;
                var type = comp.GetType();
                if (type.FullName != "Spine.Unity.SkeletonGraphic" && type.FullName != "Spine.Unity.SkeletonAnimation") continue;
                var stateProp = type.GetProperty("AnimationState", BindingFlags.Public | BindingFlags.Instance);
                var state = stateProp != null ? stateProp.GetValue(comp) : null;
                if (state == null) { Debug.LogWarning($"[YggScenePlayer] {type.Name} on {child.name} has no AnimationState (SkeletonDataAsset assigned?)"); return; }
                var setAnim = state.GetType().GetMethod("SetAnimation", new[] { typeof(int), typeof(string), typeof(bool) });
                if (setAnim == null) return;
                var entry = setAnim.Invoke(state, new object[] { cue.trackIndex, cue.animationName, cue.loop });
                if (entry != null)
                {
                    var entryType = entry.GetType();
                    if (cue.mixDuration >= 0f)
                        entryType.GetProperty("MixDuration")?.SetValue(entry, cue.mixDuration);
                    if (Math.Abs(cue.speed - 1f) > 1e-4f)
                        entryType.GetProperty("TimeScale")?.SetValue(entry, cue.speed);
                }
                return;
            }
            Debug.LogWarning($"[YggScenePlayer] no Spine component on {child.name} — attach SkeletonGraphic/SkeletonAnimation and assign its SkeletonDataAsset.");
        }
    }
}
`;
}

export function scenePlayerEditorSource() {
  return `// Auto-generated by YGG Toolkit Scene Studio.
using System;
using System.Collections.Generic;
using System.IO;
using UnityEditor;
using UnityEngine;

namespace Ygg.SceneStudio
{
    [CustomEditor(typeof(YggScenePlayer))]
    // Fully qualified base class: projects with a DLL exposing a root-level
    // "Editor" namespace would otherwise shadow UnityEditor.Editor (CS0118).
    public class YggScenePlayerEditor : UnityEditor.Editor
    {
        [Serializable] class DescriptorNode
        {
            public string path;
            public string kind;
            public string spineData;
            public string spineSkin;
            public string spineAnim;
            public bool spineLoop = true;
        }
        [Serializable] class Descriptor { public string variant; public List<DescriptorNode> nodes; }

        public override void OnInspectorGUI()
        {
            DrawDefaultInspector();
            var player = (YggScenePlayer)target;

            EditorGUILayout.Space();
            if (GUILayout.Button("Auto-assign Spine Data"))
            {
                AutoAssignSpineData(player);
            }
            if (GUILayout.Button("Build Unity Timeline from baked clip"))
            {
                YggSceneTimelineBuilder.Build(player);
            }

            using (new EditorGUI.DisabledScope(!Application.isPlaying))
            {
                EditorGUILayout.BeginHorizontal();
                if (GUILayout.Button("▶ Play")) player.Play();
                if (GUILayout.Button("■ Stop")) player.Stop();
                EditorGUILayout.EndHorizontal();
            }
            if (!Application.isPlaying)
                EditorGUILayout.HelpBox("Enter Play Mode to use Play/Stop. 'Auto-assign Spine Data' wires each spine layer's SkeletonDataAsset (generated by spine-unity on import). 'Build Unity Timeline' creates a TimelineAsset next to the prefab and wires the PlayableDirector.", MessageType.Info);
        }

        /// Finds the SkeletonDataAsset spine-unity generated for each exported
        /// spine layer (named "<json>_SkeletonData") and assigns it through
        /// SerializedObject — no compile-time spine dependency needed.
        static void AutoAssignSpineData(YggScenePlayer player)
        {
            if (player.descriptor == null)
            {
                Debug.LogWarning("[Ygg] No descriptor TextAsset on the player — cannot auto-assign.");
                return;
            }
            Descriptor desc;
            try { desc = JsonUtility.FromJson<Descriptor>(player.descriptor.text); }
            catch (Exception e) { Debug.LogError("[Ygg] Failed to parse descriptor: " + e.Message); return; }
            if (desc?.nodes == null) return;

            var dataAssets = new List<(string name, string path)>();
            foreach (var guid in AssetDatabase.FindAssets("t:SkeletonDataAsset"))
            {
                var p = AssetDatabase.GUIDToAssetPath(guid);
                dataAssets.Add((Path.GetFileNameWithoutExtension(p), p));
            }

            int assigned = 0, missing = 0;
            foreach (var node in desc.nodes)
            {
                if (string.IsNullOrEmpty(node.spineData)) continue;
                var child = string.IsNullOrEmpty(node.path) ? player.transform : player.transform.Find(node.path);
                if (child == null) { Debug.LogWarning($"[Ygg] spine node not found: {node.path}"); missing++; continue; }

                // Find an existing spine component — or create one, which runs
                // spine-unity's own editor defaults (auto-detected materials).
                MonoBehaviour spineComp = null;
                foreach (var comp in child.GetComponents<MonoBehaviour>())
                {
                    if (comp == null) continue;
                    var fn = comp.GetType().FullName;
                    if (fn == "Spine.Unity.SkeletonGraphic" || fn == "Spine.Unity.SkeletonAnimation") { spineComp = comp; break; }
                }
                if (spineComp == null)
                {
                    string wantedType = desc.variant == "world"
                        ? "Spine.Unity.SkeletonAnimation, spine-unity"
                        : "Spine.Unity.SkeletonGraphic, spine-unity";
                    var t = Type.GetType(wantedType);
                    if (t == null)
                    {
                        Debug.LogWarning($"[Ygg] spine-unity runtime not found ({wantedType}) — cannot create component for {node.path}.");
                        missing++;
                        continue;
                    }
                    spineComp = (MonoBehaviour)Undo.AddComponent(child.gameObject, t);
                    Debug.Log($"[Ygg] {node.path}: added {t.Name}", spineComp);
                }

                var so = new SerializedObject(spineComp);
                var dataProp = so.FindProperty("skeletonDataAsset");
                if (dataProp == null) { missing++; continue; }

                if (dataProp.objectReferenceValue == null)
                {
                    string want = node.spineData + "_SkeletonData";
                    string found = null;
                    foreach (var (name, p) in dataAssets)
                    {
                        if (string.Equals(name, want, StringComparison.OrdinalIgnoreCase)) { found = p; break; }
                        if (found == null && name.StartsWith(node.spineData, StringComparison.OrdinalIgnoreCase)) found = p;
                    }
                    if (found == null)
                    {
                        Debug.LogWarning($"[Ygg] No SkeletonDataAsset found for '{node.spineData}' — has spine-unity imported the skeleton yet?");
                        missing++;
                        continue;
                    }
                    dataProp.objectReferenceValue = AssetDatabase.LoadAssetAtPath<UnityEngine.Object>(found);
                    Debug.Log($"[Ygg] {node.path} ← {found}", spineComp);
                }

                SetString(so, "initialSkinName", string.IsNullOrEmpty(node.spineSkin) ? "default" : node.spineSkin);
                SetString(so, "startingAnimation", node.spineAnim);   // SkeletonGraphic
                SetString(so, "_animationName", node.spineAnim);      // SkeletonAnimation
                SetBool(so, "startingLoop", node.spineLoop);
                SetBool(so, "loop", node.spineLoop);
                so.ApplyModifiedProperties();
                EditorUtility.SetDirty(spineComp);
                assigned++;
            }
            Debug.Log($"[Ygg] Spine auto-assign done: {assigned} wired, {missing} unresolved.");
        }

        static void SetString(SerializedObject so, string prop, string value)
        {
            var p = so.FindProperty(prop);
            if (p != null && value != null) p.stringValue = value;
        }

        static void SetBool(SerializedObject so, string prop, bool value)
        {
            var p = so.FindProperty(prop);
            if (p != null) p.boolValue = value;
        }
    }
}
`;
}

export function timelineBuilderSource() {
  return `// Auto-generated by YGG Toolkit Scene Studio.
//
// Builds a Unity TimelineAsset from the baked AnimationClip + spine cues
// using the official Timeline API — no fragile serialized Timeline YAML.
// When the spine.timeline package is installed, spine cues become real
// Spine Animation State tracks; otherwise they stay on the YggScenePlayer.
//
// Compiles to a stub when the com.unity.timeline package is missing
// (YGG_HAS_TIMELINE comes from the asmdef versionDefines) so importing the
// package never breaks the project — ▶ Play then samples the baked clip
// directly instead of driving a PlayableDirector.
#if !YGG_HAS_TIMELINE
using UnityEngine;

namespace Ygg.SceneStudio
{
    public static class YggSceneTimelineBuilder
    {
        public static void Build(YggScenePlayer player)
        {
            Debug.LogWarning("[Ygg] The com.unity.timeline package is not installed — add it via Package Manager to build a Timeline. ▶ Play works without it (direct clip sampling).");
        }
    }
}
#else
using System;
using System.IO;
using UnityEditor;
using UnityEngine;
using UnityEngine.Playables;
using UnityEngine.Timeline;

namespace Ygg.SceneStudio
{
    public static class YggSceneTimelineBuilder
    {
        public static void Build(YggScenePlayer player)
        {
            if (player == null) return;
            var director = player.director != null ? player.director : player.GetComponent<PlayableDirector>();
            if (director == null) { Debug.LogError("[Ygg] No PlayableDirector on the scene player."); return; }

            string basePath = GetAssetFolder(player);
            string assetPath = Path.Combine(basePath, player.gameObject.name + "_Timeline.playable").Replace('\\\\', '/');

            var timeline = AssetDatabase.LoadAssetAtPath<TimelineAsset>(assetPath);
            if (timeline == null)
            {
                timeline = ScriptableObject.CreateInstance<TimelineAsset>();
                AssetDatabase.CreateAsset(timeline, assetPath);
            }
            else
            {
                foreach (var t in timeline.GetRootTracks())
                    timeline.DeleteTrack(t);
            }

            timeline.fixedDuration = player.durationSeconds;
            timeline.durationMode = TimelineAsset.DurationMode.FixedLength;

            if (player.transformClip != null)
            {
                var track = timeline.CreateTrack<AnimationTrack>(null, "Baked transforms");
                var clip = track.CreateClip(player.transformClip);
                clip.start = 0;
                clip.duration = Math.Max(0.05f, player.transformClip.length);
                var animator = player.GetComponent<Animator>();
                if (animator != null) director.SetGenericBinding(track, animator);
            }

            TryBuildSpineTracks(player, timeline, director);

            director.playableAsset = timeline;
            EditorUtility.SetDirty(timeline);
            EditorUtility.SetDirty(director);
            AssetDatabase.SaveAssets();
            Debug.Log($"[Ygg] Timeline built at {assetPath}", timeline);
        }

        static string GetAssetFolder(YggScenePlayer player)
        {
            // Next to the prefab when the player comes from one, else the clip's folder.
            string src = null;
            var prefab = PrefabUtility.GetCorrespondingObjectFromSource(player.gameObject);
            if (prefab != null) src = AssetDatabase.GetAssetPath(prefab);
            if (string.IsNullOrEmpty(src) && player.transformClip != null) src = AssetDatabase.GetAssetPath(player.transformClip);
            if (string.IsNullOrEmpty(src)) src = "Assets";
            return Path.GetDirectoryName(src);
        }

        static void TryBuildSpineTracks(YggScenePlayer player, TimelineAsset timeline, PlayableDirector director)
        {
            if (player.spineCues == null || player.spineCues.Count == 0) return;
            var trackType = Type.GetType("Spine.Unity.Playables.SpineAnimationStateTrack, spine-unity") ??
                            Type.GetType("Spine.Unity.Playables.SpineAnimationStateTrack, Spine.Unity.Playables");
            if (trackType == null)
            {
                Debug.Log("[Ygg] spine.timeline package not found — spine cues stay on YggScenePlayer (still played at runtime).");
                return;
            }
            Debug.Log("[Ygg] spine.timeline detected. Automatic Spine track building is best-effort; cues also remain on YggScenePlayer as fallback.");
            // Building typed Spine clips via reflection across spine.timeline
            // versions is intentionally conservative: we create one track per
            // target so animators can drag the clips in, names prefilled.
            foreach (var cue in player.spineCues)
            {
                var track = timeline.CreateTrack(trackType, null, $"Spine: {cue.target} · {cue.animationName} @ {cue.start:0.##}s");
                var child = string.IsNullOrEmpty(cue.target) ? player.transform : player.transform.Find(cue.target);
                if (child == null) continue;
                foreach (var comp in child.GetComponents<MonoBehaviour>())
                {
                    if (comp == null) continue;
                    var fn = comp.GetType().FullName;
                    if (fn == "Spine.Unity.SkeletonGraphic" || fn == "Spine.Unity.SkeletonAnimation")
                    {
                        director.SetGenericBinding(track, comp);
                        break;
                    }
                }
            }
        }
    }
}
#endif
`;
}
